// Static site generator for wee4techsolutions.com
// Usage: node src/build.mjs   (writes HTML + SEO files to the repository root)
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join, dirname } from 'node:path';
import { SITE, layout, abs } from './site.mjs';
import { SERVICES, COURSES, COURSE_FACTS } from './content.mjs';
import { allPages, REDIRECTS } from './pages.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const TODAY = new Date().toISOString().slice(0, 10);
const out = (file, content) => writeFileSync(join(ROOT, file), content);

const pages = allPages();
for (const page of pages) {
  page.modified = TODAY;
  out(page.path, layout(page, { services: SERVICES, courses: COURSES }));
}

// Netlify: permanent redirects for old URLs, plus headers
out('_redirects', `# Generated by src/build.mjs — old URLs → new pages (301)
${Object.entries(REDIRECTS).flatMap(([from, to]) => [from, from.replace(/\.html$/, '')].map((f) => `/${f}  /${to === 'index.html' ? '' : to}  301`)).join('\n')}
/course-details_C%2B%2B.html  /cpp-programming-course.html  301
`);

out('_headers', `/*
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  X-Frame-Options: SAMEORIGIN
  Permissions-Policy: camera=(), microphone=(), geolocation=()

/assets/img/*
  Cache-Control: public, max-age=2592000

/assets/css/*
  Cache-Control: public, max-age=86400

/assets/js/*
  Cache-Control: public, max-age=86400
`);

// sitemap.xml
const priority = (p) => (p === 'index.html' ? '1.0' : ['services.html', 'courses.html'].includes(p) || SERVICES.some((s) => s.slug === p) ? '0.9' : COURSES.some((c) => c.slug === p) ? '0.8' : p.includes('privacy') || p.includes('terms') ? '0.3' : '0.7');
out('sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${pages.filter((p) => !p.noindex).map((p) => `  <url><loc>${abs(p.path)}</loc><lastmod>${TODAY}</lastmod><priority>${priority(p.path)}</priority></url>`).join('\n')}
</urlset>
`);

// robots.txt — allow search engines and AI assistants to crawl and cite the site
out('robots.txt', `# ${SITE.name}
User-agent: *
Allow: /
Disallow: /src/

# AI search & answer engines are welcome
User-agent: GPTBot
Allow: /
User-agent: OAI-SearchBot
Allow: /
User-agent: ChatGPT-User
Allow: /
User-agent: ClaudeBot
Allow: /
User-agent: Claude-SearchBot
Allow: /
User-agent: PerplexityBot
Allow: /
User-agent: Google-Extended
Allow: /
User-agent: Applebot-Extended
Allow: /
User-agent: Bingbot
Allow: /

Sitemap: ${SITE.url}/sitemap.xml
`);

// llms.txt — concise, machine-readable summary for LLMs (https://llmstxt.org)
const md = (s) => s.replace(/<[^>]+>/g, '');
out('llms.txt', `# ${SITE.name}

> ${SITE.name} is a software development, IT consulting and IT training company founded in ${SITE.founded} and based in Chennai, Tamil Nadu, India. It builds custom business software, e-commerce stores, web applications and Android/iOS mobile apps; maintains and supports existing applications; provides IT consulting, cloud and AI solutions, digital marketing and IT staffing; and runs job-oriented programming courses.

- Address: ${SITE.address.street}, ${SITE.address.city}, ${SITE.address.region} ${SITE.address.postal}, India
- Phone: ${SITE.phone}
- Email: ${SITE.email} (careers: ${SITE.hrEmail})
- Serves: Chennai, India and international clients

## Services

${SERVICES.map((s) => `- [${s.name}](${abs(s.slug)}): ${md(s.answer.a)}`).join('\n')}

## Training courses (${COURSE_FACTS.duration} each, certificate on completion)

${COURSES.map((c) => `- [${c.name}](${abs(c.slug)}): ${c.summary}`).join('\n')}

## Company

- [About](${abs('about.html')}): Company background, values and clients
- [Careers](${abs('career.html')}): Job applications for Chennai, Coimbatore, Bangalore, Hyderabad and Pune
- [Contact](${abs('contact.html')}): Enquiry form, phone, email and map
`);

// Web app manifest
out('site.webmanifest', JSON.stringify({
  name: SITE.name,
  short_name: 'Wee4 Tech',
  start_url: './',
  display: 'standalone',
  background_color: '#ffffff',
  theme_color: '#122120',
  icons: [
    { src: 'assets/img/icon-192.png', sizes: '192x192', type: 'image/png' },
    { src: 'assets/img/icon-512.png', sizes: '512x512', type: 'image/png' },
  ],
}, null, 2));

console.log(`Built ${pages.length} pages, ${Object.keys(REDIRECTS).length} redirects, sitemap, robots.txt, llms.txt`);
