// Service and course content. Edit copy here, then run `node src/build.mjs`.

export const SERVICES = [
  {
    slug: 'custom-software-development.html',
    card: 'Bespoke business applications, portals, APIs and integrations designed around your workflows.',
    name: 'Custom Software Development',
    menu: 'Bespoke software built around your process',
    icon: 'code',
    serviceType: 'Custom software development',
    title: 'Custom Software Development Company in Chennai | Wee4 Tech',
    description: 'Custom software development in Chennai: business applications, ERP/CRM modules, portals and APIs designed, built, tested and supported by Wee4 Tech Solutions.',
    h1: 'Custom software development, built around how your business works',
    lead: 'We design, build and launch software that fits your workflows — not the other way round. From a first prototype to an enterprise system, one accountable team owns the result.',
    answer: {
      q: 'What is custom software development?',
      a: 'Custom software development is the process of designing, building and maintaining software for one organisation’s specific needs, instead of adapting an off-the-shelf product. Wee4 Tech Solutions delivers custom software for businesses in Chennai and worldwide: requirements, UX design, development, testing, deployment and long-term support.',
    },
    intro: [
      'Off-the-shelf tools are fine until your process no longer fits them. Teams end up juggling spreadsheets, duplicate data entry and workarounds that cost hours every week. Custom software removes that friction by modelling your real process — your approvals, your pricing rules, your reports.',
      'Our team handles the full lifecycle: we map the problem, agree on scope and milestones, ship working software in short iterations, and stay on to maintain and improve it after launch.',
    ],
    included: [
      { t: 'Business & enterprise applications', d: 'Internal tools, ERP and CRM modules, inventory, billing, HR and workflow automation.' },
      { t: 'Customer portals & SaaS products', d: 'Secure, multi-user web platforms with roles, dashboards and subscription logic.' },
      { t: 'APIs & system integration', d: 'Connect payment gateways, accounting software, CRMs, ERPs and third-party services so data flows automatically.' },
      { t: 'Legacy modernisation', d: 'Re-platform ageing desktop or PHP systems to modern, maintainable web architecture — without losing data.' },
      { t: 'UI/UX design', d: 'Wireframes and clickable prototypes validated with real users before a line of production code is written.' },
      { t: 'QA & testing', d: 'Manual and automated testing, performance checks and security reviews before every release.' },
    ],
    forWho: ['Startups building an MVP or first product', 'SMEs replacing spreadsheets and manual processes', 'Enterprises that need a dedicated team for a new module', 'E-commerce and retail brands that have outgrown plug-ins'],
    tech: ['React', 'Angular', 'Node.js', 'Express', '.NET / C#', 'Java / Spring', 'Python / Django', 'PHP / Laravel', 'MySQL', 'SQL Server', 'MongoDB', 'PostgreSQL', 'AWS', 'Azure', 'Docker', 'REST & GraphQL APIs'],
    why: ['A single accountable team from discovery to support', 'Fixed-scope or time-and-materials engagement — your choice', 'You own the source code and IP', 'Weekly demos so you always see real progress', 'Documentation and handover included'],
    faqs: [
      { q: 'How much does custom software development cost?', a: 'Cost depends on scope, integrations and timeline. After a free discovery call we share a written estimate broken down by feature and milestone, so you can prioritise what matters most. Larger platforms can be phased across releases to spread the investment.' },
      { q: 'How long does it take to build custom software?', a: 'A focused MVP typically takes 8–12 weeks. Larger business systems are delivered in phases, with a usable release every few weeks rather than one big launch at the end.' },
      { q: 'Will I own the source code?', a: 'Yes. On full payment, the source code, designs and documentation belong to you. We can host and maintain it, or hand it over to your internal team.' },
      { q: 'Do you provide support after launch?', a: 'Yes. We offer <a href="software-maintenance-support.html">software maintenance and support</a> plans covering bug fixes, security updates, monitoring and new features.' },
      { q: 'Do you work with clients outside Chennai?', a: 'Yes. We are based in Chennai and work with clients across India and abroad through video calls, shared project boards and regular demos.' },
    ],
    related: ['mobile-app-development.html', 'web-app-development.html', 'software-maintenance-support.html'],
  },
  {
    slug: 'web-app-development.html',
    card: 'Fast, SEO-ready business websites, e-commerce stores and web applications that turn visitors into customers.',
    name: 'Website & Web App Development',
    menu: 'Websites, e-commerce & web applications',
    icon: 'devices',
    serviceType: 'Website and web application development',
    title: 'Website & Web App Development Company in Chennai | Wee4 Tech',
    description: 'Fast, SEO-ready websites, e-commerce stores and web applications built in Chennai by Wee4 Tech Solutions using React, Next.js, Node.js and WordPress.',
    h1: 'Website & web app development that turns visitors into customers',
    lead: 'Business websites, e-commerce stores, portals and progressive web apps — designed for speed, search visibility and conversions from day one.',
    answer: {
      q: 'What does a web development company do?',
      a: 'A web development company plans, designs, builds and launches websites and browser-based applications. Wee4 Tech Solutions builds responsive business websites, e-commerce stores, customer portals and progressive web apps, with SEO, performance and analytics set up before launch.',
    },
    intro: [
      'Your website is often the first conversation a customer has with your brand. If it is slow, hard to use on a phone or invisible on Google, it quietly costs you leads.',
      'We build modern, mobile-first websites and web apps using proven frameworks, with Core Web Vitals, accessibility and structured data treated as requirements — not afterthoughts.',
    ],
    included: [
      { t: 'Business websites', d: 'Fast, responsive company websites with a CMS your team can update without a developer.' },
      { t: 'E-commerce development', d: 'Online stores with product catalogues, payment gateways (Razorpay, PayU, Stripe), shipping and order management.' },
      { t: 'Web applications & portals', d: 'Dashboards, booking systems, customer and vendor portals with secure logins and roles.' },
      { t: 'Progressive web apps (PWAs)', d: 'Web apps that load fast, work offline and can be installed on a phone like a native app.' },
      { t: 'Technical SEO built in', d: 'Clean URLs, schema markup, sitemaps, page speed and analytics configured before launch.' },
      { t: 'Redesign & migration', d: 'Modernise an outdated site while preserving rankings with proper redirects and content mapping.' },
    ],
    forWho: ['Businesses that need a credible, fast website', 'Retail and D2C brands selling online', 'Service companies that need booking or customer portals', 'Companies whose current website is slow or outdated'],
    tech: ['HTML5 & CSS3', 'JavaScript / TypeScript', 'React', 'Next.js', 'Angular', 'Node.js', 'Express', 'PHP / Laravel', 'WordPress', 'Shopify', 'MongoDB', 'MySQL'],
    why: ['Mobile-first, accessible design', 'Performance budgets and Core Web Vitals targets', 'SEO and analytics ready at launch', 'Clear handover so your team can manage content', 'Ongoing support and improvements available'],
    faqs: [
      { q: 'How long does it take to build a business website?', a: 'A typical 5–10 page business website takes 3–5 weeks from content sign-off. E-commerce stores and custom web apps take longer depending on features and integrations.' },
      { q: 'Will my new website be SEO-friendly?', a: 'Yes. Every site we build ships with semantic HTML, fast loading, mobile optimisation, meta tags, XML sitemaps, schema.org structured data and Google Analytics. For ongoing ranking growth, see our <a href="digital-marketing.html">digital marketing and SEO services</a>.' },
      { q: 'Can you redesign my existing website without losing Google rankings?', a: 'Yes. We audit current rankings and URLs, map old pages to new ones, set up 301 redirects and monitor Search Console after launch to protect your traffic.' },
      { q: 'Do you also build mobile apps?', a: 'Yes. See our <a href="mobile-app-development.html">mobile app development services</a> for Android and iOS apps. We often build the website, web admin panel and mobile app together on one shared backend.' },
    ],
    related: ['mobile-app-development.html', 'digital-marketing.html', 'software-maintenance-support.html'],
  },
  {
    slug: 'mobile-app-development.html',
    card: 'Android and iOS apps — cross-platform with Flutter or React Native, or fully native — from idea to Play Store and App Store.',
    name: 'Mobile App Development',
    menu: 'Android, iOS & cross-platform apps',
    icon: 'smartphone',
    serviceType: 'Mobile application development',
    title: 'Mobile App Development Company in Chennai | Android & iOS',
    description: 'Mobile app development in Chennai: Android, iOS and cross-platform apps with Flutter and React Native. Design, development, store launch and support.',
    h1: 'Mobile app development for Android & iOS',
    lead: 'We design, build and launch mobile apps your customers enjoy using — and keep them fast, secure and up to date after they go live on Google Play and the App Store.',
    answer: {
      q: 'What is mobile app development?',
      a: 'Mobile app development is the process of designing, building, testing and publishing applications for smartphones and tablets running Android or iOS. Wee4 Tech Solutions develops cross-platform apps with Flutter and React Native, as well as native Android (Kotlin) and iOS (Swift) apps, and handles backend APIs, admin panels, store publishing and ongoing maintenance.',
    },
    intro: [
      'A good app puts your business one tap away from your customers — for ordering, booking, tracking, payments or loyalty. A poor one gets uninstalled within a day. The difference is in the planning, the user experience and the engineering behind it.',
      'We usually recommend cross-platform development so one codebase serves both Android and iOS, cutting cost and time to market. When an app needs deep device features or maximum performance, we build natively.',
    ],
    included: [
      { t: 'Cross-platform apps', d: 'Flutter or React Native apps that run on Android and iOS from a single codebase.' },
      { t: 'Native Android & iOS apps', d: 'Kotlin and Swift development when you need maximum performance or device-specific features.' },
      { t: 'App UI/UX design', d: 'User flows, wireframes and clickable prototypes that follow Material Design and Apple guidelines.' },
      { t: 'Backend, APIs & admin panel', d: 'Secure APIs, databases, push notifications and a web admin panel to manage users, orders and content.' },
      { t: 'Integrations', d: 'Payments (Razorpay, Stripe, UPI), maps and location, OTP login, chat, analytics and third-party APIs.' },
      { t: 'Store launch & app maintenance', d: 'Google Play and App Store submission, OS-version updates, crash monitoring and new features.' },
    ],
    forWho: ['Startups launching an app-based product or MVP', 'Retail, restaurant and D2C brands that want a shopping or ordering app', 'Service businesses that need booking, tracking or field-staff apps', 'Companies with a website that now need a companion mobile app'],
    tech: ['Flutter', 'Dart', 'React Native', 'Kotlin', 'Swift', 'Firebase', 'Node.js', '.NET APIs', 'REST & GraphQL', 'MongoDB', 'MySQL', 'Google Maps', 'Razorpay / Stripe', 'Push notifications'],
    why: ['One team for app, backend and admin panel', 'Clickable prototype before development starts', 'Regular test builds on your own phone', 'Store submission handled for you', 'Maintenance plans for OS updates and new features'],
    faqs: [
      { q: 'Should I build a native app or a cross-platform app?', a: 'For most business apps, cross-platform (Flutter or React Native) is the best choice: one codebase for Android and iOS, faster delivery and lower cost. Native development makes sense for apps that rely heavily on device hardware, advanced graphics or platform-specific features. We recommend the right approach after understanding your requirements.' },
      { q: 'How long does it take to develop a mobile app?', a: 'A focused MVP app typically takes 8–14 weeks including design, development, testing and store submission. Apps with complex features, integrations or multiple user roles are delivered in phases.' },
      { q: 'How much does it cost to build a mobile app?', a: 'It depends on the number of screens and features, integrations, user roles and whether you need an admin panel. After a free consultation we share a feature-wise estimate so you can decide what goes into the first release.' },
      { q: 'Do you publish the app on Google Play and the App Store?', a: 'Yes. We prepare store listings, screenshots and privacy details, and handle submission and review for both Google Play and the Apple App Store.' },
      { q: 'Do you maintain the app after launch?', a: 'Yes. Android and iOS release new versions every year, so apps need regular updates. Our <a href="software-maintenance-support.html">maintenance plans</a> cover OS compatibility, bug fixes, crash monitoring and new features.' },
    ],
    related: ['web-app-development.html', 'custom-software-development.html', 'software-maintenance-support.html'],
  },
  {
    slug: 'software-maintenance-support.html',
    card: 'Bug fixes, security updates, monitoring and enhancements that keep live software healthy — even if someone else built it.',
    name: 'Software Maintenance & Support',
    menu: 'Bug fixes, updates, monitoring & enhancements',
    icon: 'wrench',
    serviceType: 'Software maintenance and support',
    title: 'Software Maintenance & Support Services in Chennai | Wee4 Tech',
    description: 'Software maintenance and support: bug fixes, security patches, monitoring, performance tuning and new features for web apps and business software. Monthly plans.',
    h1: 'Software maintenance & support that keeps your systems healthy',
    lead: 'Development does not end at launch. We keep your applications secure, fast and up to date — and keep improving them as your business changes. We also take over systems built by other teams.',
    answer: {
      q: 'What is software maintenance and support?',
      a: 'Software maintenance and support is the ongoing work of fixing defects, applying security and framework updates, monitoring uptime, improving performance and adding small features after an application goes live. Wee4 Tech Solutions provides monthly maintenance plans for websites, web apps, mobile apps and business software — including systems built by other vendors.',
    },
    intro: [
      'Unmaintained software decays: libraries go out of date, security holes appear, integrations break when third-party APIs change, and small bugs pile up into lost revenue.',
      'Our maintenance plans give you a dedicated team that knows your system, responds to issues quickly and plans improvements with you every month.',
    ],
    included: [
      { t: 'Corrective maintenance', d: 'Bug fixing and root-cause analysis, with priority response for production issues.' },
      { t: 'Security & updates', d: 'Framework, library, server and SSL updates; vulnerability patching and backups.' },
      { t: 'Monitoring & uptime', d: 'Uptime, error and performance monitoring with alerts, so problems are caught before customers notice.' },
      { t: 'Performance optimisation', d: 'Database tuning, caching and front-end speed work to keep pages and APIs fast.' },
      { t: 'Enhancements', d: 'Small features, reports and UI improvements delivered from a monthly hours bank.' },
      { t: 'Legacy application takeover', d: 'We audit, document and stabilise software originally built by another team or freelancer.' },
    ],
    forWho: ['Businesses whose original developer is no longer available', 'Companies with live apps but no in-house IT team', 'Product teams that want to focus on new features', 'Organisations running older PHP, .NET or Java systems'],
    tech: ['PHP / Laravel', '.NET', 'Java', 'Node.js', 'Python', 'React / Angular', 'WordPress', 'MySQL / SQL Server', 'MongoDB', 'AWS / Azure', 'Linux & IIS servers', 'Git & CI/CD'],
    why: ['Agreed response times for critical issues', 'Monthly report of work done and system health', 'Flexible plans — scale hours up or down', 'Full documentation of your system as we learn it', 'One partner for both maintenance and new development'],
    faqs: [
      { q: 'What does a software maintenance plan include?', a: 'Typically bug fixes, security and dependency updates, backups, uptime and error monitoring, performance checks and a monthly allocation of hours for small enhancements. We tailor the plan to how critical the system is to your business.' },
      { q: 'Can you maintain software that another company built?', a: 'Yes. We start with a short code and infrastructure audit, document what we find, fix urgent risks and then move to a regular maintenance cycle.' },
      { q: 'What are the four types of software maintenance?', a: 'Corrective (fixing bugs), adaptive (updating for new platforms, browsers or regulations), perfective (improving performance and usability) and preventive (refactoring and updates that stop future problems). Our plans cover all four.' },
      { q: 'How quickly do you respond to critical issues?', a: 'Response times are agreed in your plan. Production-down issues are prioritised over all other work, and you get a direct contact rather than a ticket queue.' },
    ],
    related: ['mobile-app-development.html', 'web-app-development.html', 'cloud-ai-solutions.html'],
  },
  {
    slug: 'it-consulting.html',
    card: 'Technology roadmaps, architecture reviews and digital transformation plans you can act on.',
    name: 'IT Consulting & Services',
    menu: 'Technology strategy, architecture & audits',
    icon: 'compass',
    serviceType: 'IT consulting',
    title: 'IT Consulting Services in Chennai | Technology Strategy | Wee4 Tech',
    description: 'IT consulting for SMEs and enterprises: technology roadmaps, software architecture, digital transformation, cloud readiness and code audits by Wee4 Tech Solutions.',
    h1: 'IT consulting that turns technology into business results',
    lead: 'Independent advice on what to build, buy, fix or retire. We help you make confident technology decisions and then help you execute them.',
    answer: {
      q: 'What are IT consulting services?',
      a: 'IT consulting services help an organisation plan, choose and implement technology to meet its business goals. Wee4 Tech Solutions provides technology roadmaps, software architecture reviews, digital transformation planning, cloud readiness assessments, vendor selection and code audits for businesses in Chennai and beyond.',
    },
    intro: [
      'Many technology problems are really decision problems: which platform to choose, whether to rebuild or refactor, how to automate a process, how to scale without overspending.',
      'Our consultants are hands-on engineers. Recommendations come with effort estimates, risks and a practical plan — and, if you want, the team to deliver it.',
    ],
    included: [
      { t: 'Technology strategy & roadmap', d: 'A prioritised 6–18 month plan aligned with business goals and budget.' },
      { t: 'Digital transformation', d: 'Identify manual processes to automate and systems to connect for measurable efficiency gains.' },
      { t: 'Architecture & code review', d: 'Assess scalability, security, maintainability and technical debt in existing software.' },
      { t: 'Cloud readiness & migration planning', d: 'Evaluate workloads, estimate cloud costs and plan a low-risk migration.' },
      { t: 'Build vs buy & vendor selection', d: 'Compare SaaS options and custom builds on cost, fit and long-term risk.' },
      { t: 'Virtual CTO support', d: 'Ongoing technical leadership for startups and SMEs without a full-time CTO.' },
    ],
    forWho: ['Founders validating a product idea and tech stack', 'SMEs planning digitisation or automation', 'Companies unhappy with an existing vendor or system', 'Leadership teams preparing to scale or raise funding'],
    tech: ['Solution architecture', 'Cloud (AWS, Azure, GCP)', 'Microservices & APIs', 'Data & analytics', 'DevOps & CI/CD', 'Security best practices', 'AI adoption', 'ERP & CRM platforms'],
    why: ['Engineers who build, not just advise', 'Vendor-neutral recommendations', 'Written deliverables you can act on', 'Optional delivery by the same team', 'Engagements from a one-week audit to ongoing advisory'],
    faqs: [
      { q: 'Why should a small business hire an IT consultant?', a: 'A consultant helps you avoid expensive mistakes — choosing the wrong platform, over-building, or buying tools that do not integrate. A short engagement usually costs far less than rebuilding a system that was planned poorly.' },
      { q: 'What deliverables do I get from an IT consulting engagement?', a: 'Depending on scope: a current-state assessment, a prioritised roadmap, architecture diagrams, cost and effort estimates, risk register and recommended next steps.' },
      { q: 'Can you also implement your recommendations?', a: 'Yes. Our consulting team works alongside our <a href="custom-software-development.html">development</a> and <a href="cloud-ai-solutions.html">cloud</a> teams, so the plan can move straight into delivery if you choose.' },
      { q: 'Do you offer a free initial consultation?', a: 'Yes. The first call is free. We will understand your situation and tell you honestly whether and how we can help.' },
    ],
    related: ['cloud-ai-solutions.html', 'custom-software-development.html', 'it-staffing.html'],
  },
  {
    slug: 'cloud-ai-solutions.html',
    card: 'Cloud migration, DevOps automation and practical AI — chatbots, document automation and forecasting.',
    name: 'Cloud & AI Solutions',
    menu: 'Cloud migration, DevOps & AI automation',
    icon: 'cloud',
    serviceType: 'Cloud computing and artificial intelligence solutions',
    title: 'Cloud & AI Solutions: Migration, DevOps & AI | Wee4 Tech',
    description: 'Cloud migration, DevOps and practical AI solutions — chatbots, document automation, predictive analytics — delivered by Wee4 Tech Solutions, Chennai.',
    h1: 'Cloud & AI solutions that scale your business, not your costs',
    lead: 'Move to the cloud with confidence, automate deployments, and put AI to work on real business problems — from customer support to forecasting.',
    answer: {
      q: 'How can cloud and AI help a business?',
      a: 'Cloud computing lets a business run applications on scalable, pay-as-you-go infrastructure instead of owning servers. AI applies machine learning and language models to automate tasks, predict outcomes and understand customers. Wee4 Tech Solutions helps companies migrate to AWS or Azure, set up DevOps, and build AI features such as chatbots, document processing and predictive analytics.',
    },
    intro: [
      'The cloud gives you elasticity, reliability and speed — but only when it is set up with the right architecture and cost controls. AI can save hundreds of hours — but only when it is aimed at a clear, measurable problem.',
      'We start with the business outcome, then pick the simplest technology that achieves it.',
    ],
    included: [
      { t: 'Cloud migration', d: 'Move applications and databases to AWS or Azure with minimal downtime.' },
      { t: 'DevOps & CI/CD', d: 'Automated builds, tests and deployments; containerisation with Docker; infrastructure as code.' },
      { t: 'Cost optimisation', d: 'Right-size resources, reserved capacity and monitoring to reduce cloud spend.' },
      { t: 'AI chatbots & assistants', d: 'Customer-support and internal knowledge assistants trained on your own documents.' },
      { t: 'Document & process automation', d: 'Extract data from invoices, forms and emails and push it into your systems.' },
      { t: 'Predictive analytics', d: 'Forecast demand, churn or sales using machine learning on your historical data.' },
    ],
    forWho: ['Companies running on ageing on-premise servers', 'Teams with slow, manual release processes', 'Businesses with repetitive data-entry or support workloads', 'Organisations with data they are not yet using'],
    tech: ['AWS', 'Microsoft Azure', 'Google Cloud', 'Docker', 'Kubernetes', 'GitHub Actions', 'Terraform', 'Python', 'scikit-learn', 'TensorFlow', 'LLM APIs', 'Power BI'],
    why: ['Outcome-first: every AI project has a measurable goal', 'Security and data privacy by design', 'Transparent cloud cost estimates', 'Proof-of-concept before full investment', 'Knowledge transfer to your team'],
    faqs: [
      { q: 'Is moving to the cloud cheaper than running our own servers?', a: 'Often, but not automatically. Savings come from right-sizing, auto-scaling and removing hardware maintenance. We estimate your monthly cloud bill before migration so there are no surprises.' },
      { q: 'How can a small business start using AI?', a: 'Start with one repetitive, high-volume task — answering common customer questions, reading invoices, or categorising leads. We build a small proof-of-concept, measure the time saved, and only then scale it.' },
      { q: 'Is our data safe when using AI tools?', a: 'We design AI solutions so that sensitive data stays within your controlled environment where required, use providers with enterprise data-protection terms, and apply access controls and logging.' },
    ],
    related: ['it-consulting.html', 'custom-software-development.html', 'software-maintenance-support.html'],
  },
  {
    slug: 'digital-marketing.html',
    card: 'SEO, AI search optimisation (GEO/AEO), Google & Meta ads and social media that generate qualified leads.',
    name: 'Digital Marketing & SEO',
    menu: 'SEO, GEO, social media & performance ads',
    icon: 'megaphone',
    serviceType: 'Digital marketing',
    title: 'Digital Marketing & SEO Agency in Chennai | Wee4 Tech',
    description: 'Digital marketing in Chennai: SEO, AI search optimisation (GEO/AEO), Google Ads, social media marketing and content that generates qualified leads. Wee4 Tech.',
    h1: 'Digital marketing & SEO that brings you qualified leads',
    lead: 'Be found on Google, in AI answers and on social media by the customers who are already looking for what you sell — and measure every rupee you spend.',
    answer: {
      q: 'What do digital marketing services include?',
      a: 'Digital marketing services promote a business online through search engine optimisation (SEO), paid search and social ads, social media management, content marketing, email marketing and analytics. Wee4 Tech Solutions also optimises brands for AI-powered search (GEO and AEO) so they appear in answers from Google AI Overviews, ChatGPT and similar assistants.',
    },
    intro: [
      'Because we are also a software company, our marketing starts with a technically sound website: fast pages, clean structure and correct schema markup. That foundation makes every campaign perform better.',
      'We focus on the metrics that matter — enquiries, sales and cost per lead — and report them in plain language every month.',
    ],
    included: [
      { t: 'Search engine optimisation (SEO)', d: 'Technical SEO, keyword research, on-page optimisation, local SEO and Google Business Profile.' },
      { t: 'GEO & AEO (AI search optimisation)', d: 'Structure content and entity data so AI assistants and answer engines cite your brand.' },
      { t: 'Google & Meta ads', d: 'Search, display and social campaigns with conversion tracking and ongoing optimisation.' },
      { t: 'Social media marketing', d: 'Content calendars, creatives and community management for Instagram, Facebook, LinkedIn and X.' },
      { t: 'Content marketing', d: 'Service pages, blogs, case studies and FAQs written to rank and to convert.' },
      { t: 'Analytics & reporting', d: 'GA4, Search Console and conversion tracking with a monthly performance report.' },
    ],
    forWho: ['Local businesses that want more enquiries from Chennai and Tamil Nadu', 'B2B companies that need a steady pipeline of leads', 'E-commerce brands scaling online sales', 'Training institutes filling batches'],
    tech: ['Google Search Console', 'Google Analytics 4', 'Google Ads', 'Meta Ads Manager', 'Google Business Profile', 'Schema.org', 'Semrush / Ahrefs', 'Canva & Figma', 'Mailchimp'],
    why: ['Technical SEO handled by developers', 'Transparent monthly reporting', 'No long lock-in contracts', 'Strategy tied to leads and revenue, not vanity metrics', 'Website fixes and marketing under one roof'],
    faqs: [
      { q: 'How long does SEO take to show results?', a: 'Technical fixes can improve visibility within weeks, but meaningful ranking and traffic growth usually takes 3–6 months of consistent work, depending on competition and your site’s starting point.' },
      { q: 'What is GEO and AEO?', a: 'Generative Engine Optimisation (GEO) and Answer Engine Optimisation (AEO) make your content easy for AI systems — Google AI Overviews, ChatGPT, Perplexity, voice assistants — to understand, trust and quote. It involves clear question-and-answer content, structured data, consistent business information and authoritative mentions across the web.' },
      { q: 'Do you offer local SEO for Chennai businesses?', a: 'Yes. We optimise your Google Business Profile, local citations, location pages and reviews strategy so you appear in the map pack and “near me” searches.' },
      { q: 'How much should I spend on digital marketing?', a: 'It depends on your goals and competition. We recommend starting with SEO fundamentals and a modest, well-tracked ad budget, then scaling the channels that produce leads at an acceptable cost.' },
    ],
    related: ['web-app-development.html', 'it-consulting.html', 'custom-software-development.html'],
  },
  {
    slug: 'it-staffing.html',
    card: 'Pre-screened developers, testers and IT specialists on contract, contract-to-hire or permanent basis.',
    name: 'IT Staffing & Resourcing',
    menu: 'Contract, permanent & dedicated teams',
    icon: 'users',
    serviceType: 'IT staffing',
    title: 'IT Staffing & Staff Augmentation Services in Chennai | Wee4 Tech',
    description: 'IT staffing in Chennai: pre-screened developers, testers and IT professionals on contract, contract-to-hire, permanent or as a dedicated team. Fast turnaround.',
    h1: 'IT staffing & staff augmentation — the right people, fast',
    lead: 'Scale your team with pre-screened developers, testers and IT specialists — on contract, contract-to-hire, permanent, or as a dedicated team managed by us.',
    answer: {
      q: 'What is IT staffing and staff augmentation?',
      a: 'IT staffing is the recruitment of technology professionals for a company’s projects, either temporarily or permanently. Staff augmentation adds skilled people to your existing team for as long as you need them. Wee4 Tech Solutions sources, screens and deploys IT talent for businesses across India, with flexible contract, contract-to-hire, permanent and dedicated-team models.',
    },
    intro: [
      'Hiring good technical people is slow and expensive, and a wrong hire costs even more. Our Staffing-as-a-Service model lets you adjust your workforce quickly as demand changes, without compromising on quality.',
      'Because we are an engineering company ourselves, candidates are assessed by practising developers — not just keyword-matched against a job description.',
    ],
    included: [
      { t: 'Manpower planning', d: 'Understand your project, team structure and skills gap before sourcing.' },
      { t: 'Job analysis & sourcing', d: 'Clear role definitions and targeted sourcing from our network and training pipeline.' },
      { t: 'Technical screening & selection', d: 'Hands-on technical evaluation and structured interviews.' },
      { t: 'Orientation & placement', d: 'Smooth onboarding so new team members are productive quickly.' },
      { t: 'Training & development', d: 'Upskilling through our own training programmes where needed.' },
      { t: 'Performance evaluation', d: 'Regular check-ins, feedback and replacement support if a placement is not the right fit.' },
    ],
    forWho: ['Companies with a project deadline and a skills gap', 'Startups that need to scale engineering quickly', 'Enterprises needing contract specialists', 'Teams that prefer contract-to-hire to reduce hiring risk'],
    tech: ['Full-stack developers', 'Frontend (React, Angular)', 'Backend (Java, .NET, Node.js, Python)', 'Mobile developers', 'QA & automation testers', 'DevOps & cloud engineers', 'Data analysts & scientists', 'UI/UX designers'],
    why: ['Candidates screened by working engineers', 'Rapid turnaround on shortlists', 'Compliance with applicable labour and payroll regulations', 'Flexible engagement models', 'Replacement support'],
    faqs: [
      { q: 'What is the difference between IT staffing and outsourcing?', a: 'With staffing or staff augmentation, professionals join and work under your team’s direction. With outsourcing, you hand over a defined project and the vendor manages delivery. We offer both — see <a href="custom-software-development.html">custom software development</a> for project-based work.' },
      { q: 'How quickly can you provide candidates?', a: 'For common skill sets we typically share a first shortlist within a few working days. Niche or senior roles can take longer.' },
      { q: 'Which engagement models do you offer?', a: 'Contract staffing, contract-to-hire, permanent placement and dedicated teams managed by Wee4 Tech.' },
      { q: 'I am a job seeker. How do I apply?', a: 'Please submit your profile on our <a href="career.html">careers page</a>. Our HR team will contact you when a suitable opening is available.' },
    ],
    related: ['it-consulting.html', 'custom-software-development.html', 'software-maintenance-support.html'],
  },
];

export const COURSES = [
  {
    slug: 'c-programming-course.html', old: 'course-details.html', img: 'course-1',
    name: 'C Programming Course', short: 'C Programming', category: 'Programming',
    title: 'C Programming Course in Chennai with Certificate | Wee4 Tech',
    description: 'Learn C programming in Chennai: variables, control statements, functions, arrays, pointers, strings, structures and files. 3-month course with certificate.',
    summary: 'C is a powerful, high-performance language that forms the foundation for many modern programming languages. This course takes you from your first program to pointers, memory allocation and file handling.',
    audience: ['College students (B.E., B.Tech, B.Sc, BCA, MCA)', 'Beginners with no prior coding experience', 'Candidates preparing for technical interviews and placements', 'Anyone planning to learn C++, Java or embedded systems'],
    outcomes: ['Write, compile and debug C programs confidently', 'Use functions, recursion and storage classes correctly', 'Master pointers, arrays and dynamic memory allocation', 'Work with strings, structures, unions and files', 'Solve common interview and aptitude coding problems'],
    prereq: 'None. Basic computer familiarity is enough.',
    faqs: [
      { q: 'Is C programming good for beginners?', a: 'Yes. C teaches how programs and memory really work, which makes learning any other language — C++, Java, Python — much easier afterwards.' },
      { q: 'How long is the C programming course?', a: 'The course runs for 3 months with 1-hour sessions and includes a certificate on completion.' },
    ],
  },
  {
    slug: 'cpp-programming-course.html', old: 'course-details_C++.html', img: 'course-2',
    name: 'C++ Programming Course', short: 'C++ Programming', category: 'Programming',
    title: 'C++ Programming Course in Chennai | OOP with C++ | Wee4 Tech',
    description: 'C++ course in Chennai covering OOP, classes, polymorphism, inheritance, exception handling, file streams and templates. 3 months with certificate.',
    summary: 'C++ is an object-oriented language widely used in system software, game development and real-time simulations. Learn OOP the right way — classes, inheritance, polymorphism and templates — with hands-on exercises.',
    audience: ['Students who know basic C and want to learn OOP', 'Engineering students preparing for placements', 'Aspiring game, systems or competitive programmers'],
    outcomes: ['Understand and apply object-oriented programming principles', 'Design classes with constructors, inheritance and polymorphism', 'Use operator and function overloading', 'Handle errors with exceptions', 'Work with file streams and templates'],
    prereq: 'Basic C knowledge is helpful but not mandatory.',
    faqs: [
      { q: 'Should I learn C before C++?', a: 'It helps, but it is not required. We cover the fundamentals at the start of the course before moving into object-oriented programming.' },
      { q: 'What can I build with C++?', a: 'Desktop applications, games, system utilities, high-performance software and solutions for competitive programming.' },
    ],
  },
  {
    slug: 'core-python-course.html', old: 'course-details_Core_Python.html', img: 'course-4',
    name: 'Core Python Course', short: 'Core Python', category: 'Programming',
    title: 'Core Python Course in Chennai for Beginners | Wee4 Tech',
    description: 'Beginner-friendly Core Python course in Chennai: data types, loops, strings, lists, tuples, dictionaries, functions, modules, files and exceptions. With certificate.',
    summary: 'Python is the most popular language for beginners, automation, data science and AI. This course builds a solid foundation in Python syntax, data structures, functions, file handling and exception handling.',
    audience: ['Complete beginners to programming', 'Students and fresh graduates', 'Working professionals who want to automate tasks', 'Anyone planning to move into data science or machine learning'],
    outcomes: ['Write clean Python programs using core syntax', 'Use lists, tuples, sets and dictionaries effectively', 'Create reusable functions, lambdas and modules', 'Read and write files and handle exceptions', 'Be ready for Advanced Python, Data Science or Django'],
    prereq: 'None.',
    faqs: [
      { q: 'Can a non-IT person learn Python?', a: 'Yes. Python’s simple, readable syntax makes it the easiest first language, and this course assumes no prior coding experience.' },
      { q: 'What should I learn after Core Python?', a: 'Continue with our <a href="advanced-python-course.html">Advanced Python course</a>, or move towards <a href="data-science-course.html">Data Science</a> or <a href="machine-learning-course.html">Machine Learning</a>.' },
    ],
  },
  {
    slug: 'advanced-python-course.html', old: 'course-details_Advanced_Python.html', img: 'course-3',
    name: 'Advanced Python Course', short: 'Advanced Python', category: 'Programming',
    title: 'Advanced Python Course in Chennai | OOP, Databases, NumPy | Wee4 Tech',
    description: 'Advanced Python training in Chennai: OOP, SQL and MongoDB, regular expressions, multithreading, networking, Tkinter GUI and NumPy. Certificate included.',
    summary: 'Take your Python skills to a professional level. Covers object-oriented programming, databases (SQL and MongoDB), regular expressions, multithreading, socket programming, GUI development and NumPy — plus interview preparation.',
    audience: ['Learners who have completed Core Python', 'Developers moving into backend or automation roles', 'Students preparing for Python developer interviews'],
    outcomes: ['Build object-oriented Python applications', 'Connect Python to SQL and MongoDB databases', 'Use regular expressions, threads and sockets', 'Create desktop GUIs with Tkinter', 'Work with NumPy arrays and matrices'],
    prereq: 'Core Python or equivalent knowledge.',
    faqs: [
      { q: 'What jobs can I get after Advanced Python?', a: 'Python developer, backend developer, automation engineer and junior data analyst roles, among others. It is also the foundation for data science and machine learning.' },
      { q: 'Does the course include interview preparation?', a: 'Yes. The final module covers Python career paths plus commonly asked interview questions.' },
    ],
  },
  {
    slug: 'java-course.html', old: 'course-details_Java.html', img: 'course-5',
    name: 'Java Programming Course', short: 'Java', category: 'Programming',
    title: 'Core Java Course in Chennai with Certificate | Wee4 Tech',
    description: 'Core Java training in Chennai: OOP, encapsulation, inheritance, polymorphism, abstraction, exceptions, arrays, strings, collections and multithreading.',
    summary: 'Java powers enterprise applications, Android apps and large-scale backend systems. This Core Java course covers OOP concepts, exception handling, strings, the Collections framework, multithreading and lambdas.',
    audience: ['Students and freshers targeting software developer jobs', 'Programmers switching to enterprise development', 'Aspiring Android or Spring Boot developers'],
    outcomes: ['Apply all four OOP pillars in Java', 'Use arrays, String and StringBuilder effectively', 'Work with List, Set and Queue collections', 'Handle exceptions properly', 'Understand multithreading, wrapper classes and lambdas'],
    prereq: 'None, though basic programming knowledge helps.',
    faqs: [
      { q: 'Is Java still in demand?', a: 'Yes. Java remains one of the most widely used languages for enterprise software, banking systems and Android development, with steady demand for Java developers.' },
      { q: 'Does this course cover Spring Boot?', a: 'This course focuses on Core Java, which is the prerequisite for Spring and Spring Boot. Contact us about advanced Java batches.' },
    ],
  },
  {
    slug: 'mern-stack-course.html', old: 'course-details_Mern.html', img: 'course-6',
    name: 'Full Stack Web Development (MERN) Course', short: 'Full Stack (MERN)', category: 'Web Development',
    title: 'MERN Stack Course in Chennai | Full Stack Web Development | Wee4 Tech',
    description: 'Full stack web development course in Chennai: HTML, CSS, JavaScript, Bootstrap, PHP, MySQL, MongoDB, React, Node.js and Express. Build real projects.',
    summary: 'Become a full stack web developer. Start with HTML, CSS, JavaScript and Bootstrap, learn server-side development with PHP and MySQL, then build modern applications with the MERN stack — MongoDB, Express.js, React and Node.js.',
    audience: ['Beginners who want a career in web development', 'Graduates from any stream looking to enter IT', 'Front-end developers who want to learn the backend', 'Freelancers and entrepreneurs building their own products'],
    outcomes: ['Build responsive websites with HTML, CSS, Flexbox, Grid and Bootstrap', 'Program interactive pages with JavaScript and the DOM', 'Create React applications with hooks, routing and Redux basics', 'Build REST APIs with Node.js and Express', 'Store data in MongoDB and MySQL'],
    prereq: 'None. Basic computer skills are enough.',
    faqs: [
      { q: 'What is the MERN stack?', a: 'MERN stands for MongoDB, Express.js, React and Node.js — a JavaScript-based stack used to build complete web applications, from the database to the user interface.' },
      { q: 'Can I get a job after a MERN stack course?', a: 'Full stack and React developers are in strong demand. With a solid project portfolio from this course, learners can apply for junior front-end, back-end or full stack developer roles.' },
    ],
  },
  {
    slug: 'data-science-course.html', old: 'course-details_DataScience.html', img: 'course-2',
    name: 'Data Science Course', short: 'Data Science', category: 'AI & Data',
    title: 'Data Science Course in Chennai with Python | Wee4 Tech',
    description: 'Data science course in Chennai: Python, NumPy, Pandas, data cleaning, Matplotlib and Seaborn visualisation, real-time projects and interview preparation.',
    summary: 'Learn to analyse data, extract insights and make data-driven decisions. The course covers Python from the ground up, Pandas for data wrangling, visualisation with Matplotlib and Seaborn, and real-time projects.',
    audience: ['Graduates aiming for data analyst or data scientist roles', 'Professionals who work with Excel and want to go further', 'Engineers moving into analytics'],
    outcomes: ['Program in Python for data work', 'Clean, merge, group and reshape data with Pandas', 'Handle missing data and dates', 'Create clear charts with Matplotlib and Seaborn', 'Complete real-time projects for your portfolio'],
    prereq: 'None. Python is taught from the beginning.',
    faqs: [
      { q: 'Do I need a maths background for data science?', a: 'Basic school-level maths is enough to start. The course focuses on practical data handling and visualisation, introducing statistics as needed.' },
      { q: 'What is the difference between data science and machine learning?', a: 'Data science covers collecting, cleaning, analysing and visualising data to find insights. Machine learning, a subset, builds models that learn from data to make predictions. See our <a href="machine-learning-course.html">Machine Learning course</a>.' },
    ],
  },
  {
    slug: 'machine-learning-course.html', old: 'course-details_machinelearning.html', img: 'course-1',
    name: 'Machine Learning Course', short: 'Machine Learning', category: 'AI & Data',
    title: 'Machine Learning Course in Chennai with Python | Wee4 Tech',
    description: 'Machine learning course in Chennai: Python, Pandas, visualisation, regression, classification, clustering, PCA, model evaluation and real-time projects.',
    summary: 'A comprehensive introduction to building intelligent systems with data. Learn Python and Pandas, then supervised learning (regression and classification), unsupervised learning (clustering, PCA), model evaluation and an introduction to deep learning.',
    audience: ['Graduates targeting ML engineer or data scientist roles', 'Python developers moving into AI', 'Professionals who want to apply ML in their domain'],
    outcomes: ['Prepare and explore data with Pandas and visualisation', 'Build regression and classification models', 'Apply clustering and dimensionality reduction', 'Evaluate and tune models with grid search', 'Save models and understand bagging, boosting and deep learning basics'],
    prereq: 'None required; Python is covered. Comfort with basic maths helps.',
    faqs: [
      { q: 'Which algorithms are covered?', a: 'Linear and non-linear regression, logistic regression, decision trees, random forest, K-nearest neighbours, support vector machines, Naive Bayes, K-means and hierarchical clustering, and PCA.' },
      { q: 'Is machine learning a good career in India?', a: 'Yes. Demand for ML and AI skills is growing across IT services, product companies, finance, healthcare and e-commerce.' },
    ],
  },
];

export const COURSE_FACTS = { duration: '3 months', session: '1 hour per session', certificate: 'Yes, on completion' };

export const TESTIMONIALS = [
  { text: 'Partnering with Wee4 Tech Solutions transformed our workflow. Their custom solutions streamlined our 3D rendering process, saving us time while enhancing output quality. The team was professional, responsive, and truly understood our industry needs.', name: 'Suresh Kumar', role: 'Founder' },
  { text: 'We needed a robust e-commerce platform, and Wee4 Tech delivered beyond expectations. Their expertise improved our site’s speed, usability, and overall customer experience. Sales have noticeably increased since the launch!', name: 'Sneha R', role: 'CEO' },
  { text: 'Working with Wee4 Tech was a smooth and rewarding experience. They revamped our online store with user-friendly features and a modern design. Our customers love the new interface, and we’ve seen a significant boost in engagement and conversions.', name: 'Karthik S', role: 'Entrepreneur' },
];

export const CLIENTS = [
  { name: 'Roshan Bags', url: 'https://roshanbags.com/', img: 'assets/img/optimized/client-roshan.webp', w: 363, h: 90 },
  { name: '3D Render Shop', url: 'https://3drendershop.com/', img: 'assets/img/optimized/client-3drender.webp', w: 198, h: 84 },
  { name: 'Suvaiyini', url: 'https://suvaiyini.com/', img: 'assets/img/optimized/client-suvaiyini.webp', w: 179, h: 160 },
  { name: 'Twinstep', url: null, img: 'assets/img/optimized/client-twinstep.webp', w: 129, h: 106 },
];
