// Service and course content. Edit copy here, then run `node src/build.mjs`.

export const SERVICES = [
  {
    slug: 'custom-software-development.html',
    extra: 'custom',
    card: 'Bespoke business applications, portals, APIs and integrations designed around your workflows.',
    name: 'Custom Software Development',
    menu: 'Bespoke software built around your process',
    icon: 'code',
    serviceType: 'Custom software development',
    title: 'Custom Software Development Company in Chennai | Wee4 Tech',
    description: 'Custom software development in Chennai: business applications, ERP/CRM modules, portals and APIs designed, built, tested and supported by Wee4 Tech Solutions.',
    h1: 'Custom software development, built around how your business works',
    lead: 'We design, build and launch software that fits your workflows — not the other way round. From a first prototype to an enterprise system, one accountable team owns the result.',
    answer: {
      q: 'What is custom software development?',
      a: 'Custom software development is the process of designing, building and maintaining software for one organisation’s specific needs, instead of adapting an off-the-shelf product. Wee4 Tech Solutions delivers custom software for businesses in Chennai and worldwide: requirements, UX design, development, testing, deployment and long-term support.',
    },
    intro: [
      'Off-the-shelf tools are fine until your process no longer fits them. Teams end up juggling spreadsheets, duplicate data entry and workarounds that cost hours every week. Custom software removes that friction by modelling your real process — your approvals, your pricing rules, your reports.',
      'Our team handles the full lifecycle: we map the problem, agree on scope and milestones, ship working software in short iterations, and stay on to maintain and improve it after launch.',
    ],
    included: [
      { t: 'Business & enterprise applications', d: 'Internal tools, ERP and CRM modules, inventory, billing, HR and workflow automation.' },
      { t: 'Customer portals & SaaS products', d: 'Secure, multi-user web platforms with roles, dashboards and subscription logic.' },
      { t: 'APIs & system integration', d: 'Connect payment gateways, accounting software, CRMs, ERPs and third-party services so data flows automatically.' },
      { t: 'Legacy modernisation', d: 'Re-platform ageing desktop or PHP systems to modern, maintainable web architecture — without losing data.' },
      { t: 'UI/UX design', d: 'Wireframes and clickable prototypes validated with real users before a line of production code is written.' },
      { t: 'QA & testing', d: 'Manual and automated testing, performance checks and security reviews before every release.' },
    ],
    forWho: ['Startups building an MVP or first product', 'SMEs replacing spreadsheets and manual processes', 'Enterprises that need a dedicated team for a new module', 'E-commerce and retail brands that have outgrown plug-ins'],
    tech: ['React', 'Angular', 'Node.js', 'Express', '.NET / C#', 'Java / Spring', 'Python / Django', 'PHP / Laravel', 'MySQL', 'SQL Server', 'MongoDB', 'PostgreSQL', 'AWS', 'Azure', 'Docker', 'REST & GraphQL APIs'],
    why: ['A single accountable team from discovery to support', 'Fixed-scope or time-and-materials engagement — your choice', 'You own the source code and IP', 'Weekly demos so you always see real progress', 'Documentation and handover included'],
    faqs: [
      { q: 'How much does custom software development cost?', a: 'Cost depends on scope, integrations and timeline. After a free discovery call we share a written estimate broken down by feature and milestone, so you can prioritise what matters most. Larger platforms can be phased across releases to spread the investment.' },
      { q: 'How long does it take to build custom software?', a: 'A focused MVP typically takes 8–12 weeks. Larger business systems are delivered in phases, with a usable release every few weeks rather than one big launch at the end.' },
      { q: 'Will I own the source code?', a: 'Yes. On full payment, the source code, designs and documentation belong to you. We can host and maintain it, or hand it over to your internal team.' },
      { q: 'Do you provide support after launch?', a: 'Yes. We offer <a href="software-maintenance-support.html">software maintenance and support</a> plans covering bug fixes, security updates, monitoring and new features.' },
      { q: 'Do you work with clients outside Chennai?', a: 'Yes. We are based in Chennai and work with clients across India and abroad through video calls, shared project boards and regular demos.' },
    ],
    related: ['mobile-app-development-chennai.html', 'web-development-company-chennai.html', 'software-maintenance-support.html'],
  },
  {
    slug: 'ecommerce-development-company-chennai.html',
    card: 'Online stores that load fast, rank on Google and connect to your payments, shipping and inventory — Shopify, WooCommerce or custom.',
    name: 'E-commerce Development',
    menu: 'Shopify, WooCommerce, custom & B2B stores',
    icon: 'cart',
    serviceType: 'E-commerce website development',
    extra: 'ecommerce',
    waText: 'Hi Wee4 Tech, I need an e-commerce website for my business.',
    ctaLabel: 'Get a store estimate in 24 hours',
    title: 'E-commerce Development Company in Chennai | Shopify & Custom',
    description: 'E-commerce website development in Chennai: fast Shopify, WooCommerce and custom stores with Razorpay, shipping and inventory sync. Store estimate in 24 hours.',
    h1: 'E-commerce development company in Chennai',
    lead: 'We build online stores that load fast on mobile, rank on Google and plug into your payments, shipping, inventory and GST billing — then help you grow sales after launch.',
    answer: {
      q: 'What does an e-commerce development company do?',
      a: 'An e-commerce development company designs, builds and launches online stores, and connects them to payment gateways, shipping partners, inventory and accounting systems. Wee4 Tech Solutions builds Shopify, WooCommerce and custom e-commerce websites for retail brands, D2C businesses and distributors in Chennai and across India, including B2B dealer ordering portals.',
    },
    intro: [
      'Most online stores lose sales in the same places: slow product pages on mobile, a checkout that asks for too much, stock that does not match the shop floor, and orders that someone has to re-type into billing. We fix those first.',
      'We pick the platform that fits your business — Shopify for speed to market, WooCommerce for flexibility on a budget, or a custom build when you need dealer pricing, complex catalogues or deep integrations — and we stay on after launch to keep the store fast, secure and selling.',
    ],
    included: [
      { t: 'Shopify store development', d: 'Theme setup or custom theme, apps, product import and Indian payment and shipping configuration.' },
      { t: 'WooCommerce development', d: 'WordPress stores with custom features, speed optimisation and secure hosting.' },
      { t: 'Custom & headless e-commerce', d: 'React/Next.js storefronts on a custom or headless backend when off-the-shelf platforms hold you back.' },
      { t: 'B2B & dealer ordering portals', d: 'Customer-specific price lists, credit limits, bulk ordering and reorder from order history.' },
      { t: 'Integrations', d: 'Razorpay, PayU, UPI and COD; Shiprocket and courier APIs; Tally/Zoho billing; WhatsApp order alerts; marketplace sync.' },
      { t: 'Migration & redesign', d: 'Move from an old platform or rebuild a slow store without losing products, customers, orders or Google rankings.' },
    ],
    forWho: ['Retail and D2C brands selling online or planning to', 'Offline retailers and showrooms in Chennai going online', 'Distributors and wholesalers who take dealer orders on WhatsApp or phone', 'Stores that are slow, hard to manage or losing mobile shoppers'],
    tech: ['Shopify', 'WooCommerce', 'Next.js', 'React', 'Node.js', '.NET', 'Razorpay', 'PayU', 'UPI', 'Shiprocket', 'Tally / Zoho', 'Google Analytics 4', 'Meta Pixel', 'Schema.org'],
    why: ['Store estimate within 24 hours', 'Mobile speed and SEO set up before launch', 'Indian payments, shipping and GST handled', 'You own the store, domain and data', 'Support and growth help after launch'],
    faqs: [
      { q: 'How much does an e-commerce website cost in India?', a: 'It depends mainly on the platform, the number of products and custom features, and the integrations you need (payments, shipping, billing, marketplaces). A Shopify or WooCommerce store costs less than a custom build, but has ongoing platform or plugin fees. Send us your requirements and we will share a fixed, itemised quote within 24 hours.' },
      { q: 'Should I choose Shopify, WooCommerce or a custom store?', a: 'Choose Shopify to launch fast with minimal maintenance, WooCommerce if you want flexibility and lower monthly fees and are comfortable with WordPress, and a custom build if you need B2B dealer pricing, complex product configuration or deep integration with your own systems. We recommend one after understanding your catalogue, volume and budget.' },
      { q: 'How long does it take to build an online store?', a: 'A Shopify or WooCommerce store usually takes 3–6 weeks from content sign-off. Custom and B2B e-commerce platforms typically take 8–14 weeks and are delivered in phases.' },
      { q: 'Can you move my existing store to a new platform?', a: 'Yes. We migrate products, customers and order history, keep your URLs or set up 301 redirects, and check Google Search Console after launch so you do not lose rankings.' },
      { q: 'Which payment gateways and shipping partners do you integrate?', a: 'Commonly Razorpay, PayU, UPI and cash on delivery for payments, and Shiprocket or direct courier APIs for shipping. We can integrate other gateways and logistics partners your business already uses.' },
      { q: 'Will I be able to manage products and orders myself?', a: 'Yes. You get an easy admin panel to add products, update prices and stock, and process orders, plus a training session and a short guide for your team.' },
      { q: 'Can the store sync with Amazon, Flipkart or my billing software?', a: 'Yes, using platform connectors or custom APIs we can sync products, stock and orders with marketplaces and with billing software such as Tally or Zoho.' },
    ],
    related: ['web-development-company-chennai.html', 'mobile-app-development-chennai.html', 'digital-marketing.html'],
  },
  {
    slug: 'web-development-company-chennai.html',
    card: 'Customer portals, dashboards, SaaS products and fast, SEO-ready business websites built with React, Next.js and .NET.',
    name: 'Website & Web App Development',
    menu: 'Websites, e-commerce & web applications',
    icon: 'devices',
    serviceType: 'Website and web application development',
    title: 'Web Application Development Company in Chennai | Wee4 Tech',
    description: 'Web application development in Chennai: customer portals, dashboards, SaaS products and fast business websites in React, Next.js and .NET. Estimate in 24 hours.',
    h1: 'Web application development company in Chennai',
    lead: 'Business websites, e-commerce stores, portals and progressive web apps — designed for speed, search visibility and conversions from day one.',
    answer: {
      q: 'What does a web development company do?',
      a: 'A web development company plans, designs, builds and launches websites and browser-based applications. Wee4 Tech Solutions builds responsive business websites, e-commerce stores, customer portals and progressive web apps, with SEO, performance and analytics set up before launch.',
    },
    intro: [
      'Your website is often the first conversation a customer has with your brand. If it is slow, hard to use on a phone or invisible on Google, it quietly costs you leads.',
      'We build modern, mobile-first websites and web apps using proven frameworks, with Core Web Vitals, accessibility and structured data treated as requirements — not afterthoughts.',
    ],
    included: [
      { t: 'Business websites', d: 'Fast, responsive company websites with a CMS your team can update without a developer.' },
      { t: 'E-commerce front ends', d: 'Fast storefronts and custom shopping features. For complete online stores, see our e-commerce development service.' },
      { t: 'Web applications & portals', d: 'Dashboards, booking systems, customer and vendor portals with secure logins and roles.' },
      { t: 'Progressive web apps (PWAs)', d: 'Web apps that load fast, work offline and can be installed on a phone like a native app.' },
      { t: 'Technical SEO built in', d: 'Clean URLs, schema markup, sitemaps, page speed and analytics configured before launch.' },
      { t: 'Redesign & migration', d: 'Modernise an outdated site while preserving rankings with proper redirects and content mapping.' },
    ],
    forWho: ['Businesses that need a credible, fast website', 'Retail and D2C brands selling online', 'Service companies that need booking or customer portals', 'Companies whose current website is slow or outdated'],
    tech: ['HTML5 & CSS3', 'JavaScript / TypeScript', 'React', 'Next.js', 'Angular', 'Node.js', 'Express', 'PHP / Laravel', 'WordPress', 'Shopify', 'MongoDB', 'MySQL'],
    why: ['Mobile-first, accessible design', 'Performance budgets and Core Web Vitals targets', 'SEO and analytics ready at launch', 'Clear handover so your team can manage content', 'Ongoing support and improvements available'],
    faqs: [
      { q: 'How long does it take to build a business website?', a: 'A typical 5–10 page business website takes 3–5 weeks from content sign-off. E-commerce stores and custom web apps take longer depending on features and integrations.' },
      { q: 'Will my new website be SEO-friendly?', a: 'Yes. Every site we build ships with semantic HTML, fast loading, mobile optimisation, meta tags, XML sitemaps, schema.org structured data and Google Analytics. For ongoing ranking growth, see our <a href="digital-marketing.html">digital marketing and SEO services</a>.' },
      { q: 'Can you redesign my existing website without losing Google rankings?', a: 'Yes. We audit current rankings and URLs, map old pages to new ones, set up 301 redirects and monitor Search Console after launch to protect your traffic.' },
      { q: 'Do you also build mobile apps?', a: 'Yes. See our <a href="mobile-app-development-chennai.html">mobile app development services</a> for Android and iOS apps. We often build the website, web admin panel and mobile app together on one shared backend.' },
    ],
    related: ['mobile-app-development-chennai.html', 'digital-marketing.html', 'software-maintenance-support.html'],
  },
  {
    slug: 'mobile-app-development-chennai.html',
    card: 'Android and iOS apps — cross-platform with Flutter or React Native, or fully native — from idea to Play Store and App Store.',
    name: 'Mobile App Development',
    menu: 'Android, iOS & cross-platform apps',
    icon: 'smartphone',
    serviceType: 'Mobile application development',
    title: 'Mobile App Development Company in Chennai | Android & iOS',
    description: 'Mobile app development in Chennai: Android, iOS and cross-platform apps with Flutter and React Native. Design, development, store launch and support.',
    h1: 'Mobile app development company in Chennai',
    lead: 'We design, build and launch mobile apps your customers enjoy using — and keep them fast, secure and up to date after they go live on Google Play and the App Store.',
    answer: {
      q: 'What is mobile app development?',
      a: 'Mobile app development is the process of designing, building, testing and publishing applications for smartphones and tablets running Android or iOS. Wee4 Tech Solutions develops cross-platform apps with Flutter and React Native, as well as native Android (Kotlin) and iOS (Swift) apps, and handles backend APIs, admin panels, store publishing and ongoing maintenance.',
    },
    intro: [
      'A good app puts your business one tap away from your customers — for ordering, booking, tracking, payments or loyalty. A poor one gets uninstalled within a day. The difference is in the planning, the user experience and the engineering behind it.',
      'We usually recommend cross-platform development so one codebase serves both Android and iOS, cutting cost and time to market. When an app needs deep device features or maximum performance, we build natively.',
    ],
    included: [
      { t: 'Cross-platform apps', d: 'Flutter or React Native apps that run on Android and iOS from a single codebase.' },
      { t: 'Native Android & iOS apps', d: 'Kotlin and Swift development when you need maximum performance or device-specific features.' },
      { t: 'App UI/UX design', d: 'User flows, wireframes and clickable prototypes that follow Material Design and Apple guidelines.' },
      { t: 'Backend, APIs & admin panel', d: 'Secure APIs, databases, push notifications and a web admin panel to manage users, orders and content.' },
      { t: 'Integrations', d: 'Payments (Razorpay, Stripe, UPI), maps and location, OTP login, chat, analytics and third-party APIs.' },
      { t: 'Store launch & app maintenance', d: 'Google Play and App Store submission, OS-version updates, crash monitoring and new features.' },
    ],
    forWho: ['Startups launching an app-based product or MVP', 'Retail, restaurant and D2C brands that want a shopping or ordering app', 'Service businesses that need booking, tracking or field-staff apps', 'Companies with a website that now need a companion mobile app'],
    tech: ['Flutter', 'Dart', 'React Native', 'Kotlin', 'Swift', 'Firebase', 'Node.js', '.NET APIs', 'REST & GraphQL', 'MongoDB', 'MySQL', 'Google Maps', 'Razorpay / Stripe', 'Push notifications'],
    why: ['One team for app, backend and admin panel', 'Clickable prototype before development starts', 'Regular test builds on your own phone', 'Store submission handled for you', 'Maintenance plans for OS updates and new features'],
    faqs: [
      { q: 'Should I build a native app or a cross-platform app?', a: 'For most business apps, cross-platform (Flutter or React Native) is the best choice: one codebase for Android and iOS, faster delivery and lower cost. Native development makes sense for apps that rely heavily on device hardware, advanced graphics or platform-specific features. We recommend the right approach after understanding your requirements.' },
      { q: 'How long does it take to develop a mobile app?', a: 'A focused MVP app typically takes 8–14 weeks including design, development, testing and store submission. Apps with complex features, integrations or multiple user roles are delivered in phases.' },
      { q: 'How much does it cost to build a mobile app?', a: 'It depends on the number of screens and features, integrations, user roles and whether you need an admin panel. After a free consultation we share a feature-wise estimate so you can decide what goes into the first release.' },
      { q: 'Do you publish the app on Google Play and the App Store?', a: 'Yes. We prepare store listings, screenshots and privacy details, and handle submission and review for both Google Play and the Apple App Store.' },
      { q: 'Do you maintain the app after launch?', a: 'Yes. Android and iOS release new versions every year, so apps need regular updates. Our <a href="software-maintenance-support.html">maintenance plans</a> cover OS compatibility, bug fixes, crash monitoring and new features.' },
    ],
    related: ['web-development-company-chennai.html', 'custom-software-development.html', 'software-maintenance-support.html'],
  },
  {
    slug: 'software-maintenance-support.html',
    card: 'Bug fixes, security updates, monitoring and enhancements that keep live software healthy — even if someone else built it.',
    name: 'Software Maintenance & Support',
    menu: 'Bug fixes, updates, monitoring & enhancements',
    icon: 'wrench',
    serviceType: 'Software maintenance and support',
    title: 'Software Maintenance & Support Services in Chennai | Wee4 Tech',
    description: 'Software maintenance and support in Chennai: bug fixes, security patches, monitoring, performance tuning and new features for web apps. Monthly plans.',
    h1: 'Software maintenance & support that keeps your systems healthy',
    lead: 'Development does not end at launch. We keep your applications secure, fast and up to date — and keep improving them as your business changes. We also take over systems built by other teams.',
    answer: {
      q: 'What is software maintenance and support?',
      a: 'Software maintenance and support is the ongoing work of fixing defects, applying security and framework updates, monitoring uptime, improving performance and adding small features after an application goes live. Wee4 Tech Solutions provides monthly maintenance plans for websites, web apps, mobile apps and business software — including systems built by other vendors.',
    },
    intro: [
      'Unmaintained software decays: libraries go out of date, security holes appear, integrations break when third-party APIs change, and small bugs pile up into lost revenue.',
      'Our maintenance plans give you a dedicated team that knows your system, responds to issues quickly and plans improvements with you every month.',
    ],
    included: [
      { t: 'Corrective maintenance', d: 'Bug fixing and root-cause analysis, with priority response for production issues.' },
      { t: 'Security & updates', d: 'Framework, library, server and SSL updates; vulnerability patching and backups.' },
      { t: 'Monitoring & uptime', d: 'Uptime, error and performance monitoring with alerts, so problems are caught before customers notice.' },
      { t: 'Performance optimisation', d: 'Database tuning, caching and front-end speed work to keep pages and APIs fast.' },
      { t: 'Enhancements', d: 'Small features, reports and UI improvements delivered from a monthly hours bank.' },
      { t: 'Legacy application takeover', d: 'We audit, document and stabilise software originally built by another team or freelancer.' },
    ],
    forWho: ['Businesses whose original developer is no longer available', 'Companies with live apps but no in-house IT team', 'Product teams that want to focus on new features', 'Organisations running older PHP, .NET or Java systems'],
    tech: ['PHP / Laravel', '.NET', 'Java', 'Node.js', 'Python', 'React / Angular', 'WordPress', 'MySQL / SQL Server', 'MongoDB', 'AWS / Azure', 'Linux & IIS servers', 'Git & CI/CD'],
    why: ['Agreed response times for critical issues', 'Monthly report of work done and system health', 'Flexible plans — scale hours up or down', 'Full documentation of your system as we learn it', 'One partner for both maintenance and new development'],
    faqs: [
      { q: 'What does a software maintenance plan include?', a: 'Typically bug fixes, security and dependency updates, backups, uptime and error monitoring, performance checks and a monthly allocation of hours for small enhancements. We tailor the plan to how critical the system is to your business.' },
      { q: 'Can you maintain software that another company built?', a: 'Yes. We start with a short code and infrastructure audit, document what we find, fix urgent risks and then move to a regular maintenance cycle.' },
      { q: 'What are the four types of software maintenance?', a: 'Corrective (fixing bugs), adaptive (updating for new platforms, browsers or regulations), perfective (improving performance and usability) and preventive (refactoring and updates that stop future problems). Our plans cover all four.' },
      { q: 'How quickly do you respond to critical issues?', a: 'Response times are agreed in your plan. Production-down issues are prioritised over all other work, and you get a direct contact rather than a ticket queue.' },
    ],
    related: ['mobile-app-development-chennai.html', 'web-development-company-chennai.html', 'ai-development-company-chennai.html'],
  },
  {
    slug: 'it-consulting.html',
    card: 'Technology roadmaps, architecture reviews and digital transformation plans you can act on.',
    name: 'IT Consulting & Services',
    menu: 'Technology strategy, architecture & audits',
    icon: 'compass',
    serviceType: 'IT consulting',
    title: 'IT Consulting Services in Chennai | Wee4 Tech',
    description: 'IT consulting in Chennai for SMEs and enterprises: technology roadmaps, software architecture, digital transformation, cloud readiness and code audits.',
    h1: 'IT consulting that turns technology into business results',
    lead: 'Independent advice on what to build, buy, fix or retire. We help you make confident technology decisions and then help you execute them.',
    answer: {
      q: 'What are IT consulting services?',
      a: 'IT consulting services help an organisation plan, choose and implement technology to meet its business goals. Wee4 Tech Solutions provides technology roadmaps, software architecture reviews, digital transformation planning, cloud readiness assessments, vendor selection and code audits for businesses in Chennai and beyond.',
    },
    intro: [
      'Many technology problems are really decision problems: which platform to choose, whether to rebuild or refactor, how to automate a process, how to scale without overspending.',
      'Our consultants are hands-on engineers. Recommendations come with effort estimates, risks and a practical plan — and, if you want, the team to deliver it.',
    ],
    included: [
      { t: 'Technology strategy & roadmap', d: 'A prioritised 6–18 month plan aligned with business goals and budget.' },
      { t: 'Digital transformation', d: 'Identify manual processes to automate and systems to connect for measurable efficiency gains.' },
      { t: 'Architecture & code review', d: 'Assess scalability, security, maintainability and technical debt in existing software.' },
      { t: 'Cloud readiness & migration planning', d: 'Evaluate workloads, estimate cloud costs and plan a low-risk migration.' },
      { t: 'Build vs buy & vendor selection', d: 'Compare SaaS options and custom builds on cost, fit and long-term risk.' },
      { t: 'Virtual CTO support', d: 'Ongoing technical leadership for startups and SMEs without a full-time CTO.' },
    ],
    forWho: ['Founders validating a product idea and tech stack', 'SMEs planning digitisation or automation', 'Companies unhappy with an existing vendor or system', 'Leadership teams preparing to scale or raise funding'],
    tech: ['Solution architecture', 'Cloud (AWS, Azure, GCP)', 'Microservices & APIs', 'Data & analytics', 'DevOps & CI/CD', 'Security best practices', 'AI adoption', 'ERP & CRM platforms'],
    why: ['Engineers who build, not just advise', 'Vendor-neutral recommendations', 'Written deliverables you can act on', 'Optional delivery by the same team', 'Engagements from a one-week audit to ongoing advisory'],
    faqs: [
      { q: 'Why should a small business hire an IT consultant?', a: 'A consultant helps you avoid expensive mistakes — choosing the wrong platform, over-building, or buying tools that do not integrate. A short engagement usually costs far less than rebuilding a system that was planned poorly.' },
      { q: 'What deliverables do I get from an IT consulting engagement?', a: 'Depending on scope: a current-state assessment, a prioritised roadmap, architecture diagrams, cost and effort estimates, risk register and recommended next steps.' },
      { q: 'Can you also implement your recommendations?', a: 'Yes. Our consulting team works alongside our <a href="custom-software-development.html">development</a> and <a href="ai-development-company-chennai.html">cloud</a> teams, so the plan can move straight into delivery if you choose.' },
      { q: 'Do you offer a free initial consultation?', a: 'Yes. The first call is free. We will understand your situation and tell you honestly whether and how we can help.' },
    ],
    related: ['ai-development-company-chennai.html', 'custom-software-development.html', 'hire-developers-chennai.html'],
  },
  {
    slug: 'ai-development-company-chennai.html',
    card: 'Practical AI for growing businesses — WhatsApp assistants, invoice and document automation, AI search for stores — plus cloud and DevOps.',
    name: 'AI & Cloud Solutions',
    menu: 'WhatsApp AI, document automation & cloud',
    icon: 'brain',
    serviceType: 'Artificial intelligence and generative AI development',
    ctaLabel: 'Book an AI use-case call',
    waText: 'Hi Wee4 Tech, I want to explore an AI solution for my business.',
    title: 'AI Development Company in Chennai | GenAI & Automation',
    description: 'Practical AI for Chennai businesses: WhatsApp AI assistants, invoice and document automation, AI search for e-commerce. Proof of concept in 2–3 weeks.',
    h1: 'AI development company in Chennai — practical AI for growing businesses',
    lead: 'We put AI to work on the repetitive jobs that slow your team down — answering customer questions, reading invoices, finding products — and connect it to the software you already use.',
    answer: {
      q: 'How can a small or mid-sized business use AI?',
      a: 'A growing business gets the fastest return from AI on repetitive, high-volume work: answering common customer questions on WhatsApp, reading invoices and purchase orders into billing, searching product catalogues, and summarising documents. Wee4 Tech Solutions builds these generative AI solutions in Chennai using large language model APIs, connects them to your existing software, and proves the value with a short, fixed-scope proof of concept before you invest further.',
    },
    intro: [
      'Most AI projects fail because they start with the technology instead of the problem. We start with one task your team does hundreds of times a month, measure how long it takes today, and build the smallest AI solution that removes most of that work.',
      'Because we also build and maintain business software, the AI does not live in a separate demo — it is wired into your orders, CRM, store or billing system.',
    ],
    included: [
      { t: 'WhatsApp & website AI assistants', d: 'Answer product, price, stock and order-status questions 24/7, trained on your own catalogue, policies and FAQs, with hand-off to a human.' },
      { t: 'Invoice & document automation', d: 'Read invoices, purchase orders, forms and emails, extract the data and push it into Tally, Zoho or your own software.' },
      { t: 'AI for e-commerce', d: 'Smart product search, recommendations, and auto-written product descriptions for large catalogues.' },
      { t: 'Internal knowledge assistants', d: 'Let staff ask questions of manuals, SOPs and past documents instead of searching folders.' },
      { t: 'Predictive analytics', d: 'Forecast demand, stock and sales from your historical data.' },
      { t: 'Cloud & DevOps', d: 'Move apps to AWS or Azure, automate deployments with CI/CD and keep cloud costs under control.' },
    ],
    forWho: ['Businesses answering the same customer questions all day', 'Teams re-typing invoices, orders or forms into software', 'E-commerce stores with large catalogues', 'Companies that want to try AI with a small, measurable first project'],
    tech: ['OpenAI / Claude / Gemini APIs', 'Python', 'LangChain', 'Vector search', 'WhatsApp Business API', 'OCR', 'Node.js', '.NET', 'AWS', 'Azure', 'Docker', 'GitHub Actions'],
    why: ['Starts with one measurable business task', 'Fixed-scope proof of concept in 2–3 weeks', 'Connected to your existing software', 'Data privacy and access control by design', 'Maintained after launch like any other software'],
    faqs: [
      { q: 'How much does an AI chatbot or AI automation cost?', a: 'It depends on what the AI must connect to (catalogue, orders, billing), how many channels it serves (WhatsApp, website) and the usage volume, which drives the monthly AI API cost. We start with a fixed-price proof of concept so you see results before committing to a full rollout.' },
      { q: 'What is a proof of concept (PoC) and how long does it take?', a: 'A PoC is a small working version of the AI solution built on your real data for one task — for example, answering your top 50 customer questions on WhatsApp. It usually takes 2–3 weeks and shows accuracy and time saved before you invest further.' },
      { q: 'Is our business data safe with AI?', a: 'We use AI providers with business data-protection terms, send only the data needed for each task, keep sensitive records in your own systems, and add access controls and logs. Where required, we can keep processing within a specific cloud region.' },
      { q: 'How accurate is AI for customer questions or invoices?', a: 'Accuracy depends on the quality of your data and how narrow the task is. We measure it during the PoC, add human review for low-confidence answers, and only go live when results meet the target you set.' },
      { q: 'Do you also provide cloud migration and DevOps?', a: 'Yes. We migrate applications to AWS or Azure, set up automated deployments and monitoring, and optimise cloud costs.' },
    ],
    related: ['custom-software-development.html', 'ecommerce-development-company-chennai.html', 'it-consulting.html'],
  },
  {
    slug: 'digital-marketing.html',
    card: 'SEO, AI search optimisation (GEO/AEO), Google & Meta ads and social media that generate qualified leads.',
    name: 'Digital Marketing & SEO',
    menu: 'SEO, GEO, social media & performance ads',
    icon: 'megaphone',
    serviceType: 'Digital marketing',
    title: 'Digital Marketing & SEO Agency in Chennai | Wee4 Tech',
    description: 'Digital marketing in Chennai: SEO, AI search optimisation (GEO/AEO), Google Ads, social media marketing and content that generates qualified leads. Wee4 Tech.',
    h1: 'Digital marketing & SEO that brings you qualified leads',
    lead: 'Be found on Google, in AI answers and on social media by the customers who are already looking for what you sell — and measure every rupee you spend.',
    answer: {
      q: 'What do digital marketing services include?',
      a: 'Digital marketing services promote a business online through search engine optimisation (SEO), paid search and social ads, social media management, content marketing, email marketing and analytics. Wee4 Tech Solutions also optimises brands for AI-powered search (GEO and AEO) so they appear in answers from Google AI Overviews, ChatGPT and similar assistants.',
    },
    intro: [
      'Because we are also a software company, our marketing starts with a technically sound website: fast pages, clean structure and correct schema markup. That foundation makes every campaign perform better.',
      'We focus on the metrics that matter — enquiries, sales and cost per lead — and report them in plain language every month.',
    ],
    included: [
      { t: 'Search engine optimisation (SEO)', d: 'Technical SEO, keyword research, on-page optimisation, local SEO and Google Business Profile.' },
      { t: 'GEO & AEO (AI search optimisation)', d: 'Structure content and entity data so AI assistants and answer engines cite your brand.' },
      { t: 'Google & Meta ads', d: 'Search, display and social campaigns with conversion tracking and ongoing optimisation.' },
      { t: 'Social media marketing', d: 'Content calendars, creatives and community management for Instagram, Facebook, LinkedIn and X.' },
      { t: 'Content marketing', d: 'Service pages, blogs, case studies and FAQs written to rank and to convert.' },
      { t: 'Analytics & reporting', d: 'GA4, Search Console and conversion tracking with a monthly performance report.' },
    ],
    forWho: ['Local businesses that want more enquiries from Chennai and Tamil Nadu', 'B2B companies that need a steady pipeline of leads', 'E-commerce brands scaling online sales', 'Training institutes filling batches'],
    tech: ['Google Search Console', 'Google Analytics 4', 'Google Ads', 'Meta Ads Manager', 'Google Business Profile', 'Schema.org', 'Semrush / Ahrefs', 'Canva & Figma', 'Mailchimp'],
    why: ['Technical SEO handled by developers', 'Transparent monthly reporting', 'No long lock-in contracts', 'Strategy tied to leads and revenue, not vanity metrics', 'Website fixes and marketing under one roof'],
    faqs: [
      { q: 'How long does SEO take to show results?', a: 'Technical fixes can improve visibility within weeks, but meaningful ranking and traffic growth usually takes 3–6 months of consistent work, depending on competition and your site’s starting point.' },
      { q: 'What is GEO and AEO?', a: 'Generative Engine Optimisation (GEO) and Answer Engine Optimisation (AEO) make your content easy for AI systems — Google AI Overviews, ChatGPT, Perplexity, voice assistants — to understand, trust and quote. It involves clear question-and-answer content, structured data, consistent business information and authoritative mentions across the web.' },
      { q: 'Do you offer local SEO for Chennai businesses?', a: 'Yes. We optimise your Google Business Profile, local citations, location pages and reviews strategy so you appear in the map pack and “near me” searches.' },
      { q: 'How much should I spend on digital marketing?', a: 'It depends on your goals and competition. We recommend starting with SEO fundamentals and a modest, well-tracked ad budget, then scaling the channels that produce leads at an acceptable cost.' },
    ],
    related: ['web-development-company-chennai.html', 'it-consulting.html', 'custom-software-development.html'],
  },
  {
    slug: 'hire-developers-chennai.html',
    group: 'hire',
    extra: 'hire',
    card: 'Pre-vetted .NET, React, Python, Flutter and QA developers who join your team on a monthly contract. Shortlist in 72 hours.',
    name: 'Hire Developers',
    menu: '.NET, React, Python, Flutter & QA on contract',
    icon: 'users',
    serviceType: 'IT staffing and staff augmentation',
    ctaLabel: 'Request developer profiles',
    waText: 'Hi Wee4 Tech, I want to hire a developer.',
    title: 'Hire Developers in Chennai | .NET, React, Python, Flutter',
    description: 'Hire pre-vetted developers in Chennai on monthly contract: .NET, React, Python, Flutter and QA. Shortlist in 72 hours, start within a week, replacement support.',
    h1: 'Hire developers in Chennai',
    lead: 'Add pre-vetted .NET, React, Python, Flutter and QA developers to your team on a monthly contract — screened by our own engineers, shortlisted in 72 hours and ready to start within a week.',
    answer: {
      q: 'How does hiring developers through Wee4 Tech work?',
      a: 'You share the role and skills you need; Wee4 Tech Solutions shortlists pre-vetted developers from Chennai within 72 hours for common roles; you interview them; and the selected developer joins your team on a monthly contract, working on your projects under your direction. We handle payroll, compliance and replacement if a developer is not the right fit. Contract-to-hire and permanent placement are also available.',
    },
    intro: [
      'Hiring good developers is slow and expensive, and a wrong hire costs even more. Hiring through us lets you add skilled people in days, scale up or down month to month, and avoid the overhead of recruiting, payroll and notice periods.',
      'Because we are a software company ourselves, candidates are assessed by practising engineers on real coding tasks — not just keyword-matched against a job description.',
    ],
    included: [
      { t: '.NET developers', d: 'C#, ASP.NET Core, Web API, SQL Server and Azure — for new builds and legacy .NET systems.' },
      { t: 'React & Next.js developers', d: 'Front-end and full-stack developers for web apps, dashboards and e-commerce front ends.' },
      { t: 'Python developers', d: 'Django, FastAPI, automation, data processing and AI integration.' },
      { t: 'Mobile developers', d: 'Flutter and React Native developers for Android and iOS apps.' },
      { t: 'QA & automation testers', d: 'Manual and automated testing with Selenium, Playwright and API testing tools.' },
      { t: 'Contract-to-hire & permanent', d: 'Try a developer on contract before hiring them onto your own payroll.' },
    ],
    forWho: ['Companies with a deadline and not enough developers', 'Startups that need to scale engineering quickly', 'Agencies that need white-label developers', 'Teams that want to reduce hiring risk with contract-to-hire'],
    tech: ['.NET / C#', 'ASP.NET Core', 'React', 'Next.js', 'Angular', 'Node.js', 'Python', 'Django / FastAPI', 'Flutter', 'React Native', 'SQL Server', 'MySQL', 'MongoDB', 'QA automation'],
    why: ['Screened by working engineers on real tasks', 'Shortlist in 72 hours for common roles', 'Monthly contracts, scale up or down', 'Payroll and compliance handled', 'Replacement support if it is not the right fit'],
    faqs: [
      { q: 'How quickly can a developer start?', a: 'For common skills such as .NET, React, Python and Flutter we usually share a shortlist within 72 hours, and the selected developer can typically start within a week. Senior or niche roles can take longer.' },
      { q: 'What is the minimum contract period?', a: 'Contracts are monthly. We agree the minimum term and notice period with you upfront, depending on the role.' },
      { q: 'Who manages the developer day to day?', a: 'You do — the developer works on your tasks, in your tools and meetings. We handle payroll, HR, equipment and replacement, and check in regularly on performance.' },
      { q: 'How is my code and IP protected?', a: 'Developers sign NDAs and IP-assignment agreements, and all work product belongs to you. Access to your systems stays under your control.' },
      { q: 'What is the difference between hiring developers and outsourcing a project?', a: 'When you hire developers, they work under your direction. When you outsource, you hand over a defined project and we manage delivery — see <a href="custom-software-development.html">custom software development</a>. For a full team managed by us, see our <a href="dedicated-development-team.html">dedicated development team</a> model.' },
      { q: 'I am a developer looking for a job. How do I apply?', a: 'Please submit your profile on our <a href="career.html">careers page</a>. Our HR team will contact you when a suitable opening is available.' },
    ],
    related: ['dedicated-development-team.html', 'dotnet-development-company-chennai.html', 'react-development-company-chennai.html'],
  },
  {
    slug: 'dedicated-development-team.html',
    group: 'hire',
    extra: 'dedicated',
    card: 'A dedicated team of developers, QA and a project lead in Chennai, working as an extension of your company — ideal for international clients.',
    name: 'Dedicated Development Team',
    menu: 'Your own offshore team in India',
    icon: 'layers',
    serviceType: 'Dedicated software development team',
    ctaLabel: 'Book a team planning call',
    waText: 'Hi Wee4 Tech, I want to set up a dedicated development team.',
    title: 'Dedicated Development Team in India | Offshore Developers',
    description: 'Build a dedicated software team in Chennai, India: developers, QA and a project lead in your time zone, with monthly pricing and full IP ownership.',
    h1: 'Your dedicated development team in India',
    lead: 'A long-term team of developers, testers and a project lead in Chennai that works only on your product — with your tools, your processes and overlapping working hours.',
    answer: {
      q: 'What is a dedicated development team?',
      a: 'A dedicated development team is a group of software professionals — developers, testers and often a project lead — who work full-time and exclusively on one client’s product, usually on a monthly contract. Wee4 Tech Solutions provides dedicated teams from Chennai, India for companies in India, the UK, the Middle East, Europe and North America, handling hiring, payroll, infrastructure and replacement while you direct the work.',
    },
    intro: [
      'Hiring a full engineering team locally is expensive and slow. Freelancers are hard to manage and rarely stay. A dedicated team gives you the stability of in-house staff at offshore cost, with the flexibility to scale month to month.',
      'Your team members work only on your product, join your stand-ups, and use your Jira, GitHub and Slack or Teams. We take care of recruitment, HR, equipment and continuity.',
    ],
    included: [
      { t: 'Team of your size', d: 'Start with one developer or a full squad of developers, QA and a project lead.' },
      { t: 'Hand-picked members', d: 'We shortlist, you interview and approve every team member.' },
      { t: 'Time-zone overlap', d: 'Agreed daily overlap hours with UK, Europe, Middle East or US teams for calls and reviews.' },
      { t: 'Your tools and process', d: 'Scrum or Kanban in your Jira, GitHub, Azure DevOps, Slack or Teams.' },
      { t: 'Project lead & reporting', d: 'Optional project lead and weekly progress reports on delivered work.' },
      { t: 'Security & IP', d: 'NDAs, IP assignment, access control and secure development practices.' },
    ],
    forWho: ['Product companies and startups scaling engineering', 'Agencies that need reliable white-label capacity', 'International SMEs facing high local developer costs', 'Companies with long-term, evolving roadmaps'],
    tech: ['.NET / C#', 'React', 'Next.js', 'Node.js', 'Python', 'Flutter', 'React Native', 'SQL Server', 'PostgreSQL', 'MongoDB', 'AWS', 'Azure', 'Jira', 'GitHub'],
    why: ['You approve every team member', 'Monthly contracts, scale up or down', 'Overlapping hours with your time zone', 'Full IP ownership and NDAs', 'Replacement and continuity handled by us'],
    faqs: [
      { q: 'How much does a dedicated development team in India cost?', a: 'Cost depends on team size, seniority and skills. Pricing is a fixed monthly fee per team member with no hidden recruitment or infrastructure charges. Tell us the roles you need and we will send a team plan with monthly pricing.' },
      { q: 'How long does it take to set up the team?', a: 'Individual developers can usually start within one to two weeks. A full team with a project lead typically takes two to four weeks, depending on roles.' },
      { q: 'How do you handle time-zone differences?', a: 'We agree fixed overlap hours for stand-ups and reviews — for example, afternoons in India overlap with mornings in the UK and Europe, and the Middle East is only one to two hours apart. For US teams we arrange early-morning or evening overlap.' },
      { q: 'Who owns the code and IP?', a: 'You do. All team members sign NDAs and IP-assignment agreements, and all code lives in repositories you control.' },
      { q: 'Can we scale the team up or down?', a: 'Yes. Contracts are monthly, so you can add or release team members with the notice period agreed in your contract.' },
    ],
    related: ['hire-developers-chennai.html', 'dotnet-development-company-chennai.html', 'react-development-company-chennai.html'],
  },
  {
    slug: 'dotnet-development-company-chennai.html',
    group: 'hire',
    card: 'ASP.NET Core applications and APIs, legacy .NET Framework migration, and dedicated .NET developers.',
    name: '.NET Development',
    menu: 'ASP.NET Core, migration & .NET developers',
    icon: 'layers',
    serviceType: '.NET software development',
    ctaLabel: 'Get a .NET estimate',
    waText: 'Hi Wee4 Tech, I need help with a .NET project.',
    title: '.NET Development Company in Chennai | Hire ASP.NET Developers',
    description: 'ASP.NET Core development and legacy .NET migration from Chennai: APIs, enterprise apps and dedicated .NET developers for clients in India, UK, UAE and US.',
    h1: '.NET development company in Chennai',
    lead: 'We build and modernise business applications on Microsoft .NET — ASP.NET Core web apps and APIs, SQL Server databases and Azure hosting — and provide dedicated .NET developers for your team.',
    answer: {
      q: 'What does a .NET development company do?',
      a: 'A .NET development company builds and maintains software on Microsoft’s .NET platform using C#, ASP.NET Core, Entity Framework and SQL Server, often hosted on Azure. Wee4 Tech Solutions develops .NET web applications, APIs and enterprise systems, migrates legacy .NET Framework and Web Forms applications to modern .NET, and provides dedicated .NET developers from Chennai.',
    },
    intro: [
      'Many established businesses run critical systems on older .NET Framework, Web Forms or WCF code that is hard to change, hard to host and hard to hire for. Others need a new, secure API or portal built on a platform their IT team trusts.',
      'We cover both: new ASP.NET Core development, and step-by-step modernisation of legacy .NET applications without stopping the business.',
    ],
    included: [
      { t: 'ASP.NET Core web applications', d: 'Portals, dashboards and internal business systems with secure authentication and roles.' },
      { t: 'Web APIs & integrations', d: 'REST APIs for mobile apps, e-commerce and third-party systems, with documentation.' },
      { t: 'Legacy .NET migration', d: 'Move .NET Framework, Web Forms, WCF and MVC 5 applications to modern .NET, module by module.' },
      { t: 'SQL Server & database work', d: 'Schema design, performance tuning, reporting and data migration.' },
      { t: 'Azure hosting & DevOps', d: 'App Service, Azure SQL, CI/CD pipelines and monitoring.' },
      { t: 'Dedicated .NET developers', d: 'Monthly-contract .NET developers who join your team.' },
    ],
    forWho: ['Companies running ageing .NET Framework or Web Forms systems', 'Businesses that need a secure API for apps or partners', 'Microsoft-stack IT teams needing extra capacity', 'International firms hiring .NET developers offshore'],
    tech: ['C#', '.NET 8 / 9', 'ASP.NET Core', 'Web API', 'Entity Framework Core', 'Blazor', 'SQL Server', 'Azure', 'Azure DevOps', 'Docker', 'Angular', 'React'],
    why: ['New builds and legacy modernisation', 'Migration in phases, without downtime', 'Code reviews and automated tests', 'Monthly .NET developers available', 'Support after go-live'],
    faqs: [
      { q: 'Can you migrate our old .NET Framework application to .NET 8 or 9?', a: 'Yes. We assess the code, identify blockers such as Web Forms or WCF, and plan a phased migration — often running old and new modules side by side — so the business keeps running throughout.' },
      { q: 'Should we rebuild or migrate our legacy .NET system?', a: 'If the business logic is sound, migrating is usually faster and lower-risk. If the system no longer matches how you work, a rebuild may be better. We give a written recommendation after a short code assessment.' },
      { q: 'Can we hire a dedicated .NET developer?', a: 'Yes. See <a href="hire-developers-chennai.html">hire developers</a> — .NET developers can usually start within a week of selection.' },
      { q: 'Do you work with international clients?', a: 'Yes. We work with clients in India and abroad, with agreed overlap hours for UK, Middle East, Europe and US time zones.' },
    ],
    related: ['hire-developers-chennai.html', 'custom-software-development.html', 'software-maintenance-support.html'],
  },
  {
    slug: 'react-development-company-chennai.html',
    group: 'hire',
    card: 'Fast, SEO-friendly web apps, dashboards and storefronts with React and Next.js — built by us or with dedicated React developers.',
    name: 'React & Next.js Development',
    menu: 'Web apps, dashboards & headless stores',
    icon: 'code',
    serviceType: 'React and Next.js development',
    ctaLabel: 'Get a React project estimate',
    waText: 'Hi Wee4 Tech, I need help with a React / Next.js project.',
    title: 'React & Next.js Development Company in Chennai | Wee4 Tech',
    description: 'React and Next.js development in Chennai: fast, SEO-friendly web apps, dashboards and e-commerce front ends. Build with us or hire dedicated React developers.',
    h1: 'React & Next.js development company in Chennai',
    lead: 'We build fast, maintainable web applications with React and Next.js — from customer portals and dashboards to SEO-friendly marketing sites and headless storefronts.',
    answer: {
      q: 'Why use React and Next.js for a business web application?',
      a: 'React is the most widely used JavaScript library for building interactive user interfaces, and Next.js adds server rendering, routing and performance features that make React sites fast and search-engine friendly. Wee4 Tech Solutions uses React and Next.js to build web apps, dashboards, SaaS products and e-commerce front ends in Chennai, and provides dedicated React developers.',
    },
    intro: [
      'A slow, hard-to-change front end costs you users and developer time. React’s component model makes interfaces consistent and easier to extend, and Next.js makes them fast and indexable by Google.',
      'We also modernise older jQuery, AngularJS or server-rendered front ends into React step by step, so you do not have to stop and rewrite everything at once.',
    ],
    included: [
      { t: 'Web applications & dashboards', d: 'Customer portals, admin panels and data-heavy dashboards with charts and filters.' },
      { t: 'Next.js websites', d: 'SEO-friendly, fast-loading marketing sites and content platforms.' },
      { t: 'Headless e-commerce front ends', d: 'Next.js storefronts on Shopify, WooCommerce or a custom commerce backend.' },
      { t: 'SaaS product front ends', d: 'Component libraries, design systems and multi-tenant interfaces.' },
      { t: 'Front-end modernisation', d: 'Migrate jQuery, AngularJS or legacy UIs to React in phases.' },
      { t: 'Dedicated React developers', d: 'Monthly-contract React and Next.js developers for your team.' },
    ],
    forWho: ['Companies building a customer portal or SaaS product', 'Businesses whose website or app front end is slow', 'Teams moving off jQuery or AngularJS', 'Product teams that need more React developers'],
    tech: ['React', 'Next.js', 'TypeScript', 'Redux / Zustand', 'React Query', 'Tailwind CSS', 'Node.js', '.NET APIs', 'GraphQL', 'Vercel', 'AWS', 'Jest / Playwright'],
    why: ['Performance and Core Web Vitals targets', 'SEO-friendly rendering with Next.js', 'Reusable component libraries', 'Modernisation in phases', 'Dedicated React developers available'],
    faqs: [
      { q: 'Should I use React or Angular for my project?', a: 'Both are proven. React has a larger ecosystem and hiring pool and is more flexible; Angular is more opinionated and suits some large enterprise teams. We recommend based on your team, existing code and long-term plans.' },
      { q: 'Is a React website good for SEO?', a: 'A client-only React app can be hard for search engines to index. Using Next.js with server-side or static rendering solves this, which is why we use Next.js for public, SEO-critical sites.' },
      { q: 'Can you migrate our jQuery or AngularJS front end to React?', a: 'Yes. We migrate screen by screen, running old and new parts side by side, so the application stays usable throughout.' },
      { q: 'Can we hire dedicated React developers?', a: 'Yes. See <a href="hire-developers-chennai.html">hire developers</a> — React developers can usually start within a week of selection.' },
    ],
    related: ['web-development-company-chennai.html', 'ecommerce-development-company-chennai.html', 'hire-developers-chennai.html'],
  },
];

export const COURSES = [
  {
    slug: 'c-programming-course.html', old: 'course-details.html', img: 'course-1',
    name: 'C Programming Course', short: 'C Programming', category: 'Programming',
    title: 'C Programming Course in Chennai with Certificate | Wee4 Tech',
    description: 'Learn C programming in Chennai: variables, control statements, functions, arrays, pointers, strings, structures and files. 3-month course with certificate.',
    summary: 'C is a powerful, high-performance language that forms the foundation for many modern programming languages. This course takes you from your first program to pointers, memory allocation and file handling.',
    audience: ['College students (B.E., B.Tech, B.Sc, BCA, MCA)', 'Beginners with no prior coding experience', 'Candidates preparing for technical interviews and placements', 'Anyone planning to learn C++, Java or embedded systems'],
    outcomes: ['Write, compile and debug C programs confidently', 'Use functions, recursion and storage classes correctly', 'Master pointers, arrays and dynamic memory allocation', 'Work with strings, structures, unions and files', 'Solve common interview and aptitude coding problems'],
    prereq: 'None. Basic computer familiarity is enough.',
    faqs: [
      { q: 'Is C programming good for beginners?', a: 'Yes. C teaches how programs and memory really work, which makes learning any other language — C++, Java, Python — much easier afterwards.' },
      { q: 'How long is the C programming course?', a: 'The course runs for 3 months with 1-hour sessions and includes a certificate on completion.' },
    ],
  },
  {
    slug: 'cpp-programming-course.html', old: 'course-details_C++.html', img: 'course-2',
    name: 'C++ Programming Course', short: 'C++ Programming', category: 'Programming',
    title: 'C++ Programming Course in Chennai | OOP with C++ | Wee4 Tech',
    description: 'C++ course in Chennai covering OOP, classes, polymorphism, inheritance, exception handling, file streams and templates. 3 months with certificate.',
    summary: 'C++ is an object-oriented language widely used in system software, game development and real-time simulations. Learn OOP the right way — classes, inheritance, polymorphism and templates — with hands-on exercises.',
    audience: ['Students who know basic C and want to learn OOP', 'Engineering students preparing for placements', 'Aspiring game, systems or competitive programmers'],
    outcomes: ['Understand and apply object-oriented programming principles', 'Design classes with constructors, inheritance and polymorphism', 'Use operator and function overloading', 'Handle errors with exceptions', 'Work with file streams and templates'],
    prereq: 'Basic C knowledge is helpful but not mandatory.',
    faqs: [
      { q: 'Should I learn C before C++?', a: 'It helps, but it is not required. We cover the fundamentals at the start of the course before moving into object-oriented programming.' },
      { q: 'What can I build with C++?', a: 'Desktop applications, games, system utilities, high-performance software and solutions for competitive programming.' },
    ],
  },
  {
    slug: 'core-python-course.html', old: 'course-details_Core_Python.html', img: 'course-4',
    name: 'Core Python Course', short: 'Core Python', category: 'Programming',
    title: 'Core Python Course in Chennai for Beginners | Wee4 Tech',
    description: 'Beginner Core Python course in Chennai: data types, loops, strings, lists, dictionaries, functions, modules, files and exceptions. With certificate.',
    summary: 'Python is the most popular language for beginners, automation, data science and AI. This course builds a solid foundation in Python syntax, data structures, functions, file handling and exception handling.',
    audience: ['Complete beginners to programming', 'Students and fresh graduates', 'Working professionals who want to automate tasks', 'Anyone planning to move into data science or machine learning'],
    outcomes: ['Write clean Python programs using core syntax', 'Use lists, tuples, sets and dictionaries effectively', 'Create reusable functions, lambdas and modules', 'Read and write files and handle exceptions', 'Be ready for Advanced Python, Data Science or Django'],
    prereq: 'None.',
    faqs: [
      { q: 'Can a non-IT person learn Python?', a: 'Yes. Python’s simple, readable syntax makes it the easiest first language, and this course assumes no prior coding experience.' },
      { q: 'What should I learn after Core Python?', a: 'Continue with our <a href="advanced-python-course.html">Advanced Python course</a>, or move towards <a href="data-science-course.html">Data Science</a> or <a href="machine-learning-course.html">Machine Learning</a>.' },
    ],
  },
  {
    slug: 'advanced-python-course.html', old: 'course-details_Advanced_Python.html', img: 'course-3',
    name: 'Advanced Python Course', short: 'Advanced Python', category: 'Programming',
    title: 'Advanced Python Course in Chennai: OOP & NumPy | Wee4 Tech',
    description: 'Advanced Python training in Chennai: OOP, SQL and MongoDB, regular expressions, multithreading, networking, Tkinter GUI and NumPy. Certificate included.',
    summary: 'Take your Python skills to a professional level. Covers object-oriented programming, databases (SQL and MongoDB), regular expressions, multithreading, socket programming, GUI development and NumPy — plus interview preparation.',
    audience: ['Learners who have completed Core Python', 'Developers moving into backend or automation roles', 'Students preparing for Python developer interviews'],
    outcomes: ['Build object-oriented Python applications', 'Connect Python to SQL and MongoDB databases', 'Use regular expressions, threads and sockets', 'Create desktop GUIs with Tkinter', 'Work with NumPy arrays and matrices'],
    prereq: 'Core Python or equivalent knowledge.',
    faqs: [
      { q: 'What jobs can I get after Advanced Python?', a: 'Python developer, backend developer, automation engineer and junior data analyst roles, among others. It is also the foundation for data science and machine learning.' },
      { q: 'Does the course include interview preparation?', a: 'Yes. The final module covers Python career paths plus commonly asked interview questions.' },
    ],
  },
  {
    slug: 'java-course.html', old: 'course-details_Java.html', img: 'course-5',
    name: 'Java Programming Course', short: 'Java', category: 'Programming',
    title: 'Core Java Course in Chennai with Certificate | Wee4 Tech',
    description: 'Core Java training in Chennai: OOP, encapsulation, inheritance, polymorphism, abstraction, exceptions, arrays, strings, collections and multithreading.',
    summary: 'Java powers enterprise applications, Android apps and large-scale backend systems. This Core Java course covers OOP concepts, exception handling, strings, the Collections framework, multithreading and lambdas.',
    audience: ['Students and freshers targeting software developer jobs', 'Programmers switching to enterprise development', 'Aspiring Android or Spring Boot developers'],
    outcomes: ['Apply all four OOP pillars in Java', 'Use arrays, String and StringBuilder effectively', 'Work with List, Set and Queue collections', 'Handle exceptions properly', 'Understand multithreading, wrapper classes and lambdas'],
    prereq: 'None, though basic programming knowledge helps.',
    faqs: [
      { q: 'Is Java still in demand?', a: 'Yes. Java remains one of the most widely used languages for enterprise software, banking systems and Android development, with steady demand for Java developers.' },
      { q: 'Does this course cover Spring Boot?', a: 'This course focuses on Core Java, which is the prerequisite for Spring and Spring Boot. Contact us about advanced Java batches.' },
    ],
  },
  {
    slug: 'mern-stack-course.html', old: 'course-details_Mern.html', img: 'course-6',
    name: 'Full Stack Web Development (MERN) Course', short: 'Full Stack (MERN)', category: 'Web Development',
    title: 'MERN Stack & Full Stack Course in Chennai | Wee4 Tech',
    description: 'Full stack web development course in Chennai: HTML, CSS, JavaScript, Bootstrap, PHP, MySQL, MongoDB, React, Node.js and Express. Build real projects.',
    summary: 'Become a full stack web developer. Start with HTML, CSS, JavaScript and Bootstrap, learn server-side development with PHP and MySQL, then build modern applications with the MERN stack — MongoDB, Express.js, React and Node.js.',
    audience: ['Beginners who want a career in web development', 'Graduates from any stream looking to enter IT', 'Front-end developers who want to learn the backend', 'Freelancers and entrepreneurs building their own products'],
    outcomes: ['Build responsive websites with HTML, CSS, Flexbox, Grid and Bootstrap', 'Program interactive pages with JavaScript and the DOM', 'Create React applications with hooks, routing and Redux basics', 'Build REST APIs with Node.js and Express', 'Store data in MongoDB and MySQL'],
    prereq: 'None. Basic computer skills are enough.',
    faqs: [
      { q: 'What is the MERN stack?', a: 'MERN stands for MongoDB, Express.js, React and Node.js — a JavaScript-based stack used to build complete web applications, from the database to the user interface.' },
      { q: 'Can I get a job after a MERN stack course?', a: 'Full stack and React developers are in strong demand. With a solid project portfolio from this course, learners can apply for junior front-end, back-end or full stack developer roles.' },
    ],
  },
  {
    slug: 'data-science-course.html', old: 'course-details_DataScience.html', img: 'course-2',
    name: 'Data Science Course', short: 'Data Science', category: 'AI & Data',
    title: 'Data Science Course in Chennai with Python | Wee4 Tech',
    description: 'Data science course in Chennai: Python, NumPy, Pandas, data cleaning, Matplotlib and Seaborn visualisation, real-time projects and interview preparation.',
    summary: 'Learn to analyse data, extract insights and make data-driven decisions. The course covers Python from the ground up, Pandas for data wrangling, visualisation with Matplotlib and Seaborn, and real-time projects.',
    audience: ['Graduates aiming for data analyst or data scientist roles', 'Professionals who work with Excel and want to go further', 'Engineers moving into analytics'],
    outcomes: ['Program in Python for data work', 'Clean, merge, group and reshape data with Pandas', 'Handle missing data and dates', 'Create clear charts with Matplotlib and Seaborn', 'Complete real-time projects for your portfolio'],
    prereq: 'None. Python is taught from the beginning.',
    faqs: [
      { q: 'Do I need a maths background for data science?', a: 'Basic school-level maths is enough to start. The course focuses on practical data handling and visualisation, introducing statistics as needed.' },
      { q: 'What is the difference between data science and machine learning?', a: 'Data science covers collecting, cleaning, analysing and visualising data to find insights. Machine learning, a subset, builds models that learn from data to make predictions. See our <a href="machine-learning-course.html">Machine Learning course</a>.' },
    ],
  },
  {
    slug: 'machine-learning-course.html', old: 'course-details_machinelearning.html', img: 'course-1',
    name: 'Machine Learning Course', short: 'Machine Learning', category: 'AI & Data',
    title: 'Machine Learning Course in Chennai with Python | Wee4 Tech',
    description: 'Machine learning course in Chennai: Python, Pandas, visualisation, regression, classification, clustering, PCA, model evaluation and real-time projects.',
    summary: 'A comprehensive introduction to building intelligent systems with data. Learn Python and Pandas, then supervised learning (regression and classification), unsupervised learning (clustering, PCA), model evaluation and an introduction to deep learning.',
    audience: ['Graduates targeting ML engineer or data scientist roles', 'Python developers moving into AI', 'Professionals who want to apply ML in their domain'],
    outcomes: ['Prepare and explore data with Pandas and visualisation', 'Build regression and classification models', 'Apply clustering and dimensionality reduction', 'Evaluate and tune models with grid search', 'Save models and understand bagging, boosting and deep learning basics'],
    prereq: 'None required; Python is covered. Comfort with basic maths helps.',
    faqs: [
      { q: 'Which algorithms are covered?', a: 'Linear and non-linear regression, logistic regression, decision trees, random forest, K-nearest neighbours, support vector machines, Naive Bayes, K-means and hierarchical clustering, and PCA.' },
      { q: 'Is machine learning a good career in India?', a: 'Yes. Demand for ML and AI skills is growing across IT services, product companies, finance, healthcare and e-commerce.' },
    ],
  },
];

export const COURSE_FACTS = { duration: '3 months', session: '1 hour per session', certificate: 'Yes, on completion' };

export const TESTIMONIALS = [
  { text: 'Partnering with Wee4 Tech Solutions transformed our workflow. Their custom solutions streamlined our 3D rendering process, saving us time while enhancing output quality. The team was professional, responsive, and truly understood our industry needs.', name: 'Suresh Kumar', role: 'Founder' },
  { text: 'We needed a robust e-commerce platform, and Wee4 Tech delivered beyond expectations. Their expertise improved our site’s speed, usability, and overall customer experience. Sales have noticeably increased since the launch!', name: 'Sneha R', role: 'CEO' },
  { text: 'Working with Wee4 Tech was a smooth and rewarding experience. They revamped our online store with user-friendly features and a modern design. Our customers love the new interface, and we’ve seen a significant boost in engagement and conversions.', name: 'Karthik S', role: 'Entrepreneur' },
];

export const CLIENTS = [
  { name: 'Roshan Bags', url: 'https://roshanbags.com/', img: 'assets/img/optimized/client-roshan.webp', w: 363, h: 90 },
  { name: '3D Render Shop', url: 'https://3drendershop.com/', img: 'assets/img/optimized/client-3drender.webp', w: 198, h: 84 },
  { name: 'Suvaiyini', url: 'https://suvaiyini.com/', img: 'assets/img/optimized/client-suvaiyini.webp', w: 179, h: 160 },
  { name: 'Twinstep', url: null, img: 'assets/img/optimized/client-twinstep.webp', w: 129, h: 106 },
];
